import type { CodexAgentConfig } from "../../types.ts";
import type { ConfigSet } from "../validation.ts";

export const CODEX_AGENT_GENERATED_HEADER =
  "# Generated by ai-share. Do not edit directly; change config/agents.yaml instead.";

export function buildCodexAgentConfigs(config: ConfigSet): Record<string, CodexAgentConfig> {
  return Object.fromEntries(
    Object.entries(config.agents.agents).map(([agentId, source]) => {
      const model = source.model ? config.models[source.model] : undefined;
      if (source.model && !model) throw new Error(`agent '${agentId}' 引用未定义模型 '${source.model}'`);
      return [
        agentId,
        {
          name: agentId,
          description: source.description,
          ...(model ? { model: model.model_name } : {}),
          ...(source.reasoning_effort ? { model_reasoning_effort: source.reasoning_effort } : {}),
          developer_instructions: source.developer_instructions,
        },
      ];
    }),
  );
}

export function formatCodexAgentToml(agent: CodexAgentConfig): string {
  const lines = [
    CODEX_AGENT_GENERATED_HEADER,
    "",
    `name = ${JSON.stringify(agent.name)}`,
    `description = ${JSON.stringify(agent.description)}`,
    ...(agent.model ? [`model = ${JSON.stringify(agent.model)}`] : []),
    ...(agent.model_reasoning_effort
      ? [`model_reasoning_effort = ${JSON.stringify(agent.model_reasoning_effort)}`]
      : []),
    `developer_instructions = ${JSON.stringify(agent.developer_instructions)}`,
  ];
  return `${lines.join("\n")}\n`;
}
