import type {
  CodexCliConfig,
  CodexCliProvider,
  CodexMcpServer,
  GlobalYaml,
  McpYaml,
  McpServerSource,
  ModelsYaml,
  ProviderSource,
} from "../../types.ts";
import { requireEnvReferenceName } from "../env-ref.ts";
import { modelRef } from "../model-refs.ts";
import { requireString } from "../validation.ts";
import { buildInstructionsPaths } from "./instructions.ts";

export function buildCodexCliConfig(
  providerSources: Record<string, ProviderSource>,
  modelSources: ModelsYaml,
  globalConfig: GlobalYaml,
  mcpConfig: McpYaml,
  instructionsFile: string,
): CodexCliConfig {
  const modelId = modelIdFromRef(modelRef(requireString(globalConfig.model, "global.model"), modelSources));
  const modelSource = modelSources[modelId];
  const providerId = requireString(modelSource?.provider, `models.${modelId}.provider`);
  const modelReasoningEffort = reasoningEffort(modelId, modelSources);
  const windowsConfig = nonEmptyRecord(globalConfig.codex_windows);
  const shellEnvironmentPolicy = nonEmptyRecord(globalConfig.codex_shell_environment_policy);

  return {
    model: modelSource?.model_name ?? modelId,
    model_provider: providerId,
    ...(modelReasoningEffort ? { model_reasoning_effort: modelReasoningEffort } : {}),
    model_instructions_file: instructionsFile,
    ...(globalConfig.codex_allow_login_shell === undefined
      ? {}
      : { allow_login_shell: globalConfig.codex_allow_login_shell }),
    ...(windowsConfig ? { windows: windowsConfig } : {}),
    ...(shellEnvironmentPolicy ? { shell_environment_policy: shellEnvironmentPolicy } : {}),
    model_providers: buildCodexProviders(providerSources),
    ...nonEmptyMcpServers(buildCodexMcpServers(mcpConfig)),
  };
}

export function buildCodexInstructions(projectRoot: string): string {
  const linkedFiles = buildInstructionsPaths(projectRoot)
    .map((path) => `- ${path}`)
    .join("\n");
  return [
    "# Codex Instructions",
    "",
    "This file is generated by ai-share. Do not edit it directly; change the source files listed below instead.",
    "",
    "Load and follow these ai-share instruction and memory files before planning or editing:",
    "",
    linkedFiles,
    "",
    "Preserve env-only secret handling. Do not write real API keys, tokens, cookies, or private credentials into files.",
    "",
  ].join("\n");
}

export function formatCodexConfigToml(config: CodexCliConfig): string {
  const lines = [
    `model = ${tomlString(config.model)}`,
    `model_provider = ${tomlString(config.model_provider)}`,
    ...(config.model_reasoning_effort ? [`model_reasoning_effort = ${tomlString(config.model_reasoning_effort)}`] : []),
    `model_instructions_file = ${tomlString(config.model_instructions_file)}`,
    ...(config.allow_login_shell === undefined ? [] : [`allow_login_shell = ${tomlBoolean(config.allow_login_shell)}`]),
    "",
  ];

  if (config.windows && Object.keys(config.windows).length > 0) {
    lines.push("[windows]");
    if (config.windows.sandbox) lines.push(`sandbox = ${tomlString(config.windows.sandbox)}`);
    lines.push("");
  }

  if (config.shell_environment_policy && Object.keys(config.shell_environment_policy).length > 0) {
    lines.push("[shell_environment_policy]");
    if (config.shell_environment_policy.inherit) {
      lines.push(`inherit = ${tomlString(config.shell_environment_policy.inherit)}`);
    }
    if (config.shell_environment_policy.ignore_default_excludes !== undefined) {
      lines.push(`ignore_default_excludes = ${tomlBoolean(config.shell_environment_policy.ignore_default_excludes)}`);
    }
    if (config.shell_environment_policy.experimental_use_profile !== undefined) {
      lines.push(`experimental_use_profile = ${tomlBoolean(config.shell_environment_policy.experimental_use_profile)}`);
    }
    if (config.shell_environment_policy.exclude) {
      lines.push(`exclude = ${tomlStringArray(config.shell_environment_policy.exclude)}`);
    }
    if (config.shell_environment_policy.include_only) {
      lines.push(`include_only = ${tomlStringArray(config.shell_environment_policy.include_only)}`);
    }
    if (config.shell_environment_policy.set && Object.keys(config.shell_environment_policy.set).length > 0) {
      lines.push("");
      lines.push("[shell_environment_policy.set]");
      for (const [envKey, envValue] of Object.entries(config.shell_environment_policy.set)) {
        lines.push(`${tomlBareKey(envKey)} = ${tomlString(envValue)}`);
      }
    }
    lines.push("");
  }

  for (const [providerId, provider] of Object.entries(config.model_providers)) {
    lines.push(`[model_providers.${tomlBareKey(providerId)}]`);
    if (provider.name) lines.push(`name = ${tomlString(provider.name)}`);
    lines.push(`base_url = ${tomlString(provider.base_url)}`);
    lines.push(`env_key = ${tomlString(provider.env_key)}`);
    lines.push("");
  }

  for (const [serverId, server] of Object.entries(config.mcp_servers ?? {})) {
    lines.push(`[mcp_servers.${tomlBareKey(serverId)}]`);
    if (server.command) lines.push(`command = ${tomlString(server.command)}`);
    if (server.args) lines.push(`args = ${tomlStringArray(server.args)}`);
    if (server.url) lines.push(`url = ${tomlString(server.url)}`);
    if (server.bearer_token_env_var) lines.push(`bearer_token_env_var = ${tomlString(server.bearer_token_env_var)}`);
    if (server.oauth_client_id) lines.push(`oauth_client_id = ${tomlString(server.oauth_client_id)}`);
    if (server.oauth_resource) lines.push(`oauth_resource = ${tomlString(server.oauth_resource)}`);
    if (server.env && Object.keys(server.env).length > 0) {
      lines.push("");
      lines.push(`[mcp_servers.${tomlBareKey(serverId)}.env]`);
      for (const [envKey, envValue] of Object.entries(server.env)) {
        lines.push(`${tomlBareKey(envKey)} = ${tomlString(envValue)}`);
      }
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function buildCodexProviders(providerSources: Record<string, ProviderSource>): Record<string, CodexCliProvider> {
  return Object.fromEntries(
    Object.entries(providerSources).map(([providerId, provider]) => [
      providerId,
      {
        ...(provider.name ? { name: provider.name } : {}),
        base_url: requireString(provider.base_url, `providers.${providerId}.base_url`),
        env_key: requireEnvReferenceName(provider.api_key, `providers.${providerId}.api_key`),
      },
    ]),
  );
}

function buildCodexMcpServers(mcpConfig: McpYaml): Record<string, CodexMcpServer> {
  return Object.fromEntries(
    Object.entries(mcpConfig.servers ?? {}).map(([serverId, server]) => [
      serverId,
      buildCodexMcpServer(serverId, server),
    ]),
  );
}

function buildCodexMcpServer(serverId: string, server: McpServerSource): CodexMcpServer {
  if (server.transport === "http" || server.url) {
    return {
      url: requireString(server.url, `mcp.servers.${serverId}.url`),
      ...(server.bearer_token_env_var ? { bearer_token_env_var: server.bearer_token_env_var } : {}),
      ...(server.oauth_client_id ? { oauth_client_id: server.oauth_client_id } : {}),
      ...(server.oauth_resource ? { oauth_resource: server.oauth_resource } : {}),
    };
  }

  return {
    command: requireString(server.command, `mcp.servers.${serverId}.command`),
    ...(server.args ? { args: server.args } : {}),
    ...(server.env ? { env: server.env } : {}),
  };
}

function nonEmptyMcpServers(servers: Record<string, CodexMcpServer>): Pick<CodexCliConfig, "mcp_servers"> {
  return Object.keys(servers).length > 0 ? { mcp_servers: servers } : {};
}

function reasoningEffort(modelId: string, modelSources: ModelsYaml): "low" | "medium" | "high" | undefined {
  const value =
    modelSources[modelId]?.parameters?.reasoningEffort ?? modelSources[modelId]?.parameters?.reasoning_effort;
  if (value === "low" || value === "medium" || value === "high") return value;
  if (value === "max") return "high";
  return undefined;
}

function modelIdFromRef(model: string): string {
  return model.split("/").at(-1) ?? model;
}

function tomlBareKey(value: string): string {
  return /^[A-Za-z0-9_-]+$/.test(value) ? value : tomlString(value);
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlStringArray(values: string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function tomlBoolean(value: boolean): string {
  return value ? "true" : "false";
}

function nonEmptyRecord<T extends object>(value: T | undefined): T | undefined {
  return value && Object.keys(value).length > 0 ? value : undefined;
}
