import type {
  CodexCliProfileConfig,
  CodexCliProvider,
  CodexMcpServer,
  McpYaml,
  McpServerSource,
  ModelRoleMap,
  ModelsYaml,
  ProfilesYaml,
  ProviderSource,
} from "../../types.ts";
import { modelRef } from "../model-refs.ts";
import { requireRecord, requireString } from "../validation.ts";
import { buildInstructionsPaths } from "./instructions.ts";

export function buildCodexCliConfigs(
  providerSources: Record<string, ProviderSource>,
  modelSources: ModelsYaml,
  profilesConfig: ProfilesYaml,
  mcpConfig: McpYaml,
  instructionsFileForProfile: (profileId: string) => string,
): Record<string, CodexCliProfileConfig> {
  return Object.fromEntries(
    Object.keys(requireRecord(profilesConfig, "profiles")).map((profileId) => [
      profileId,
      buildCodexCliConfig(
        providerSources,
        modelSources,
        profilesConfig,
        mcpConfig,
        profileId,
        instructionsFileForProfile(profileId),
      ),
    ]),
  );
}

export function buildCodexInstructions(projectRoot: string, profileId: string): string {
  const linkedFiles = buildInstructionsPaths(projectRoot, profileId)
    .map((path) => `- ${path}`)
    .join("\n");
  return [
    "# Codex Instructions",
    "",
    "This file is generated by ai-share. Do not edit it directly; change the source files listed below instead.",
    "",
    "Load and follow these ai-share instruction and memory files before planning or editing:",
    "",
    linkedFiles,
    "",
    "Preserve env-only secret handling. Do not write real API keys, tokens, cookies, or private credentials into files.",
    "",
  ].join("\n");
}

export function formatCodexConfigToml(config: CodexCliProfileConfig): string {
  const lines = [
    `model = ${tomlString(config.model)}`,
    `model_provider = ${tomlString(config.model_provider)}`,
    ...(config.model_reasoning_effort ? [`model_reasoning_effort = ${tomlString(config.model_reasoning_effort)}`] : []),
    `model_instructions_file = ${tomlString(config.model_instructions_file)}`,
    "",
  ];

  for (const [providerId, provider] of Object.entries(config.model_providers)) {
    lines.push(`[model_providers.${tomlBareKey(providerId)}]`);
    if (provider.name) lines.push(`name = ${tomlString(provider.name)}`);
    lines.push(`base_url = ${tomlString(provider.base_url)}`);
    lines.push(`env_key = ${tomlString(provider.env_key)}`);
    lines.push("");
  }

  for (const [serverId, server] of Object.entries(config.mcp_servers ?? {})) {
    lines.push(`[mcp_servers.${tomlBareKey(serverId)}]`);
    if (server.command) lines.push(`command = ${tomlString(server.command)}`);
    if (server.args) lines.push(`args = ${tomlStringArray(server.args)}`);
    if (server.url) lines.push(`url = ${tomlString(server.url)}`);
    if (server.bearer_token_env_var) lines.push(`bearer_token_env_var = ${tomlString(server.bearer_token_env_var)}`);
    if (server.oauth_client_id) lines.push(`oauth_client_id = ${tomlString(server.oauth_client_id)}`);
    if (server.oauth_resource) lines.push(`oauth_resource = ${tomlString(server.oauth_resource)}`);
    if (server.env && Object.keys(server.env).length > 0) {
      lines.push("");
      lines.push(`[mcp_servers.${tomlBareKey(serverId)}.env]`);
      for (const [envKey, envValue] of Object.entries(server.env)) {
        lines.push(`${tomlBareKey(envKey)} = ${tomlString(envValue)}`);
      }
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function buildCodexCliConfig(
  providerSources: Record<string, ProviderSource>,
  modelSources: ModelsYaml,
  profilesConfig: ProfilesYaml,
  mcpConfig: McpYaml,
  profileId: string,
  instructionsFile: string,
): CodexCliProfileConfig {
  const profileModels = requireRecord(profilesConfig[profileId]?.models, `profiles.${profileId}.models`);
  const primaryModelRef = modelRef("primary", modelSources, profileModels);
  const primaryModelId = modelIdFromRef(primaryModelRef);
  const primaryModelSource = modelSources[primaryModelId];
  const primaryProviderId = requireString(primaryModelSource?.provider, `models.${primaryModelId}.provider`);
  const primaryReasoningEffort = reasoningEffort(profileModels, modelSources);

  return {
    model: primaryModelSource?.model_name ?? primaryModelId,
    model_provider: primaryProviderId,
    ...(primaryReasoningEffort ? { model_reasoning_effort: primaryReasoningEffort } : {}),
    model_instructions_file: instructionsFile,
    model_providers: buildCodexProviders(providerSources),
    ...nonEmptyMcpServers(buildCodexMcpServers(mcpConfig)),
  };
}

function buildCodexProviders(providerSources: Record<string, ProviderSource>): Record<string, CodexCliProvider> {
  return Object.fromEntries(
    Object.entries(providerSources).map(([providerId, provider]) => [
      providerId,
      {
        ...(provider.name ? { name: provider.name } : {}),
        base_url: requireString(provider.base_url, `providers.${providerId}.base_url`),
        env_key: envKeyName(requireString(provider.api_key, `providers.${providerId}.api_key`)),
      },
    ]),
  );
}

function buildCodexMcpServers(mcpConfig: McpYaml): Record<string, CodexMcpServer> {
  return Object.fromEntries(
    Object.entries(mcpConfig.servers ?? {}).map(([serverId, server]) => [
      serverId,
      buildCodexMcpServer(serverId, server),
    ]),
  );
}

function buildCodexMcpServer(serverId: string, server: McpServerSource): CodexMcpServer {
  if (server.transport === "http" || server.url) {
    return {
      url: requireString(server.url, `mcp.servers.${serverId}.url`),
      ...(server.bearer_token_env_var ? { bearer_token_env_var: server.bearer_token_env_var } : {}),
      ...(server.oauth_client_id ? { oauth_client_id: server.oauth_client_id } : {}),
      ...(server.oauth_resource ? { oauth_resource: server.oauth_resource } : {}),
    };
  }

  return {
    command: requireString(server.command, `mcp.servers.${serverId}.command`),
    ...(server.args ? { args: server.args } : {}),
    ...(server.env ? { env: server.env } : {}),
  };
}

function nonEmptyMcpServers(servers: Record<string, CodexMcpServer>): Pick<CodexCliProfileConfig, "mcp_servers"> {
  return Object.keys(servers).length > 0 ? { mcp_servers: servers } : {};
}

function reasoningEffort(profileModels: ModelRoleMap, modelSources: ModelsYaml): "low" | "medium" | "high" | undefined {
  const modelId = modelIdFromRef(modelRef("primary", modelSources, profileModels));
  const value =
    modelSources[modelId]?.parameters?.reasoningEffort ?? modelSources[modelId]?.parameters?.reasoning_effort;
  if (value === "low" || value === "medium" || value === "high") return value;
  if (value === "max") return "high";
  return undefined;
}

function modelIdFromRef(model: string): string {
  return model.split("/").at(-1) ?? model;
}

function envKeyName(value: string): string {
  const match = /^\$\{([A-Z0-9_]+)\}$/.exec(value);
  if (!match?.[1]) throw new Error(`api_key 必须使用 \${"{"}ENV_NAME} 格式：${value}`);
  return match[1];
}

function tomlBareKey(value: string): string {
  return /^[A-Za-z0-9_-]+$/.test(value) ? value : tomlString(value);
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlStringArray(values: string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}
