import type {
  CodexCliConfig,
  CodexCliProvider,
  CodexMcpServer,
  GlobalYaml,
  McpYaml,
  McpServerSource,
  ModelsYaml,
  ProviderSource,
} from "../../types.ts";
import { modelRef } from "../model-refs.ts";
import { requireString } from "../validation.ts";
import { buildInstructionsPaths } from "./instructions.ts";

export function buildCodexCliConfig(
  providerSources: Record<string, ProviderSource>,
  modelSources: ModelsYaml,
  globalConfig: GlobalYaml,
  mcpConfig: McpYaml,
  instructionsFile: string,
  projectRoot: string = process.cwd(),
): CodexCliConfig {
  const modelId = modelIdFromRef(modelRef(requireString(globalConfig.model, "global.model"), modelSources));
  const modelSource = modelSources[modelId];
  const providerId = requireString(modelSource?.provider, `models.${modelId}.provider`);
  const modelReasoningEffort = reasoningEffort(modelId, modelSources);

  return {
    model: modelSource?.model_name ?? modelId,
    model_provider: providerId,
    ...(modelReasoningEffort ? { model_reasoning_effort: modelReasoningEffort } : {}),
    model_instructions_file: instructionsFile,
    model_providers: buildCodexProviders(providerSources),
    ...nonEmptyMcpServers(buildCodexMcpServers(mcpConfig, projectRoot)),
  };
}

export function buildCodexInstructions(projectRoot: string): string {
  const linkedFiles = buildInstructionsPaths(projectRoot)
    .map((path) => `- ${path}`)
    .join("\n");
  return [
    "# Codex Instructions",
    "",
    "This file is generated by ai-share. Do not edit it directly; change the source files listed below instead.",
    "",
    "Load and follow these ai-share instruction and memory files before planning or editing:",
    "",
    linkedFiles,
    "",
    "Preserve env-only secret handling. Do not write real API keys, tokens, cookies, or private credentials into files.",
    "",
  ].join("\n");
}

export function formatCodexConfigToml(config: CodexCliConfig): string {
  const lines = [
    `model = ${tomlString(config.model)}`,
    `model_provider = ${tomlString(config.model_provider)}`,
    ...(config.model_reasoning_effort ? [`model_reasoning_effort = ${tomlString(config.model_reasoning_effort)}`] : []),
    `model_instructions_file = ${tomlString(config.model_instructions_file)}`,
    "",
  ];

  for (const [providerId, provider] of Object.entries(config.model_providers)) {
    lines.push(`[model_providers.${tomlBareKey(providerId)}]`);
    if (provider.name) lines.push(`name = ${tomlString(provider.name)}`);
    lines.push(`base_url = ${tomlString(provider.base_url)}`);
    lines.push(`env_key = ${tomlString(provider.env_key)}`);
    lines.push("");
  }

  for (const [serverId, server] of Object.entries(config.mcp_servers ?? {})) {
    lines.push(`[mcp_servers.${tomlBareKey(serverId)}]`);
    if (server.command) lines.push(`command = ${tomlString(server.command)}`);
    if (server.args) lines.push(`args = ${tomlStringArray(server.args)}`);
    if (server.url) lines.push(`url = ${tomlString(server.url)}`);
    if (server.bearer_token_env_var) lines.push(`bearer_token_env_var = ${tomlString(server.bearer_token_env_var)}`);
    if (server.oauth_client_id) lines.push(`oauth_client_id = ${tomlString(server.oauth_client_id)}`);
    if (server.oauth_resource) lines.push(`oauth_resource = ${tomlString(server.oauth_resource)}`);
    if (server.env && Object.keys(server.env).length > 0) {
      lines.push("");
      lines.push(`[mcp_servers.${tomlBareKey(serverId)}.env]`);
      for (const [envKey, envValue] of Object.entries(server.env)) {
        lines.push(`${tomlBareKey(envKey)} = ${tomlString(envValue)}`);
      }
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function mergeCodexConfigToml(existingToml: string | undefined, generatedToml: string): string {
  if (!existingToml) return generatedToml;

  const generated = splitTomlDocument(generatedToml);
  const existing = splitTomlDocument(existingToml);
  const generatedTopLevelLines = trimBlankEdges(generated.topLevelLines);
  const existingTopLevelLines = trimBlankEdges(
    existing.topLevelLines.filter((line) => {
      const key = topLevelAssignmentKey(line);
      return !key || !MANAGED_CODEX_TOP_LEVEL_KEYS.has(key);
    }),
  );
  const existingTables = existing.tables
    .filter((table) => !isManagedCodexTable(table.headerPath))
    .map((table) => trimBlankEdges(table.lines))
    .filter((lines) => lines.length > 0);
  const generatedTables = generated.tables
    .map((table) => trimBlankEdges(table.lines))
    .filter((lines) => lines.length > 0);

  return `${[generatedTopLevelLines, existingTopLevelLines, ...existingTables, ...generatedTables]
    .filter((lines) => lines.length > 0)
    .map((lines) => lines.join("\n"))
    .join("\n\n")
    .trimEnd()}\n`;
}

function buildCodexProviders(providerSources: Record<string, ProviderSource>): Record<string, CodexCliProvider> {
  return Object.fromEntries(
    Object.entries(providerSources).map(([providerId, provider]) => [
      providerId,
      {
        ...(provider.name ? { name: provider.name } : {}),
        base_url: requireString(provider.base_url, `providers.${providerId}.base_url`),
        env_key: envKeyName(requireString(provider.api_key, `providers.${providerId}.api_key`)),
      },
    ]),
  );
}

function buildCodexMcpServers(mcpConfig: McpYaml, projectRoot: string): Record<string, CodexMcpServer> {
  return Object.fromEntries(
    Object.entries(mcpConfig.servers ?? {})
      .filter(([, server]) => server.enabled !== false)
      .map(([serverId, server]) => [serverId, buildCodexMcpServer(serverId, server, projectRoot)]),
  );
}

function buildCodexMcpServer(serverId: string, server: McpServerSource, projectRoot: string): CodexMcpServer {
  if (server.transport === "http" || server.url) {
    return {
      url: requireString(server.url, `mcp.servers.${serverId}.url`),
      ...(server.bearer_token_env_var ? { bearer_token_env_var: server.bearer_token_env_var } : {}),
      ...(server.oauth_client_id ? { oauth_client_id: server.oauth_client_id } : {}),
      ...(server.oauth_resource ? { oauth_resource: server.oauth_resource } : {}),
    };
  }

  return {
    command: requireString(server.command, `mcp.servers.${serverId}.command`),
    ...(server.args ? { args: resolveMcpArgs(server.args, projectRoot) } : {}),
    ...(server.env ? { env: server.env } : {}),
  };
}

function resolveMcpArgs(args: string[], projectRoot: string): string[] {
  return args.map((arg, index) => (arg === "." && args[index - 1] === "--cwd" ? projectRoot : arg));
}

function nonEmptyMcpServers(servers: Record<string, CodexMcpServer>): Pick<CodexCliConfig, "mcp_servers"> {
  return Object.keys(servers).length > 0 ? { mcp_servers: servers } : {};
}

function reasoningEffort(modelId: string, modelSources: ModelsYaml): "low" | "medium" | "high" | undefined {
  const value =
    modelSources[modelId]?.parameters?.reasoningEffort ?? modelSources[modelId]?.parameters?.reasoning_effort;
  if (value === "low" || value === "medium" || value === "high") return value;
  if (value === "max") return "high";
  return undefined;
}

function modelIdFromRef(model: string): string {
  return model.split("/").at(-1) ?? model;
}

function envKeyName(value: string): string {
  const match = /^\$\{([A-Z0-9_]+)\}$/.exec(value);
  if (!match?.[1]) throw new Error(`api_key 必须使用 \${ENV_NAME} 格式：${value}`);
  return match[1];
}

function tomlBareKey(value: string): string {
  return /^[A-Za-z0-9_-]+$/.test(value) ? value : tomlString(value);
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlStringArray(values: string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

const MANAGED_CODEX_TOP_LEVEL_KEYS = new Set([
  "model",
  "model_provider",
  "model_reasoning_effort",
  "model_instructions_file",
]);

type TomlTableBlock = {
  headerPath: string;
  lines: string[];
};

type TomlDocument = {
  topLevelLines: string[];
  tables: TomlTableBlock[];
};

function splitTomlDocument(toml: string): TomlDocument {
  const lines = toml.replace(/\r\n?/g, "\n").split("\n");
  if (lines.at(-1) === "") lines.pop();

  const topLevelLines: string[] = [];
  const tables: TomlTableBlock[] = [];
  let currentTable: TomlTableBlock | undefined;

  for (const line of lines) {
    const headerPath = tableHeaderPath(line);
    if (headerPath) {
      currentTable = { headerPath, lines: [line] };
      tables.push(currentTable);
      continue;
    }

    if (currentTable) {
      currentTable.lines.push(line);
    } else {
      topLevelLines.push(line);
    }
  }

  return { topLevelLines, tables };
}

function tableHeaderPath(line: string): string | undefined {
  const match = /^\s*\[([^\]]+)\]\s*(?:#.*)?$/.exec(line);
  return match?.[1]?.trim();
}

function topLevelAssignmentKey(line: string): string | undefined {
  const match = /^\s*([A-Za-z0-9_-]+)\s*=/.exec(line);
  return match?.[1];
}

function isManagedCodexTable(headerPath: string): boolean {
  return (
    headerPath === "model_providers" ||
    headerPath.startsWith("model_providers.") ||
    headerPath === "mcp_servers" ||
    headerPath.startsWith("mcp_servers.")
  );
}

function trimBlankEdges(lines: string[]): string[] {
  let start = 0;
  let end = lines.length;
  while (start < end && lines[start]?.trim() === "") start += 1;
  while (end > start && lines[end - 1]?.trim() === "") end -= 1;
  return lines.slice(start, end);
}
