import type { EnvYaml } from "../../types.ts";

export function formatCodexEnvFile(envConfig: EnvYaml): string {
  const variables = envConfig.variables ?? {};
  const lines = [
    "# Generated by ai-share. Do not edit directly; change config/env.yaml instead.",
    "# Non-secret Codex runtime environment only. Keep API keys and tokens outside this file.",
    ...Object.entries(variables).map(([key, value]) => `${key}=${formatEnvValue(value)}`),
  ];
  return `${lines.join("\n")}\n`;
}

function formatEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:,@+\-=]+$/.test(value)) return value;
  return JSON.stringify(value);
}
