import type { EnvYaml } from "../../types.ts";

export const OPENCODE_ENV_MANAGED_BEGIN = "# BEGIN ai-share managed env";
export const OPENCODE_ENV_MANAGED_END = "# END ai-share managed env";

export function formatOpenCodeEnvFile(envConfig: EnvYaml): string {
  return formatOpenCodeEnvManagedBlock(envConfig);
}

export function formatOpenCodeEnvManagedBlock(envConfig: EnvYaml): string {
  const variables = envConfig.variables;
  const lines = [
    OPENCODE_ENV_MANAGED_BEGIN,
    "# Non-secret OpenCode runtime environment only. Keep API keys and tokens outside this file.",
    ...Object.entries(variables).map(([key, value]) => `${key}=${formatEnvValue(value)}`),
    OPENCODE_ENV_MANAGED_END,
  ];
  return `${lines.join("\n")}\n`;
}

export function buildOpenCodeEnvFileWithManagedBlock(envConfig: EnvYaml, existingContent?: string): string {
  const managedBlock = formatOpenCodeEnvManagedBlock(envConfig);
  if (!existingContent || isLegacyGeneratedEnvFile(existingContent)) return managedBlock;

  const block = managedBlockLocation(existingContent);
  if (block.status === "malformed") {
    throw new Error("OpenCode .env 中的 ai-share managed block marker 不完整或重复；请先手动修复 marker。");
  }
  if (block.status === "complete") {
    const replacement = formatManagedBlockWithLineEnding(envConfig, block.lineEnding, block.hasTrailingLineEnding);
    return `${existingContent.slice(0, block.beginIndex)}${replacement}${existingContent.slice(block.endExclusive)}`;
  }

  const lineEnding = preferredLineEnding(existingContent);
  const separator = existingContent.endsWith("\n") ? "" : lineEnding;
  return `${existingContent}${separator}${formatManagedBlockWithLineEnding(envConfig, lineEnding, true)}`;
}

export function openCodeEnvManagedBlockIsCurrent(envConfig: EnvYaml, existingContent: string | undefined): boolean {
  if (!existingContent) return false;
  return (
    extractManagedBlock(existingContent)?.replaceAll("\r\n", "\n").trimEnd() ===
    formatOpenCodeEnvManagedBlock(envConfig).trimEnd()
  );
}

export function removeOpenCodeEnvManagedBlock(existingContent: string): string {
  const block = managedBlockLocation(existingContent);
  if (block.status !== "complete") return existingContent;
  return `${existingContent.slice(0, block.beginIndex)}${existingContent.slice(block.endExclusive)}`;
}

export function openCodeEnvHasCompleteManagedBlock(existingContent: string): boolean {
  return managedBlockLocation(existingContent).status === "complete";
}

function formatEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:,@+\-=]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function isLegacyGeneratedEnvFile(content: string): boolean {
  return content.startsWith("# Generated by ai-share. Do not edit directly; change config/env.yaml instead.");
}

function extractManagedBlock(content: string): string | undefined {
  const block = managedBlockLocation(content);
  return block.status === "complete" ? content.slice(block.beginIndex, block.endExclusive) : undefined;
}

function managedBlockLocation(content: string):
  | { status: "none" | "malformed" }
  | {
      status: "complete";
      beginIndex: number;
      endExclusive: number;
      lineEnding: "\n" | "\r\n";
      hasTrailingLineEnding: boolean;
    } {
  const beginLines = exactLines(content, OPENCODE_ENV_MANAGED_BEGIN);
  const endLines = exactLines(content, OPENCODE_ENV_MANAGED_END);
  if (beginLines.length === 0 && endLines.length === 0) return { status: "none" };
  const beginLine = beginLines[0];
  const endLine = endLines[0];
  if (beginLines.length !== 1 || endLines.length !== 1 || !beginLine || !endLine) {
    return { status: "malformed" };
  }
  if (endLine.start < beginLine.start) return { status: "malformed" };
  return {
    status: "complete",
    beginIndex: beginLine.start,
    endExclusive: endLine.endExclusive,
    lineEnding: beginLine.lineEnding ?? preferredLineEnding(content),
    hasTrailingLineEnding: endLine.lineEnding !== undefined,
  };
}

type ExactLine = {
  start: number;
  endExclusive: number;
  lineEnding?: "\n" | "\r\n";
};

function exactLines(content: string, marker: string): ExactLine[] {
  const lines: ExactLine[] = [];
  let lineStart = 0;
  while (lineStart <= content.length) {
    const newlineIndex = content.indexOf("\n", lineStart);
    const rawLineEnd = newlineIndex < 0 ? content.length : newlineIndex;
    const hasCarriageReturn = rawLineEnd > lineStart && content[rawLineEnd - 1] === "\r";
    const contentEnd = hasCarriageReturn ? rawLineEnd - 1 : rawLineEnd;
    if (content.slice(lineStart, contentEnd) === marker) {
      lines.push({
        start: lineStart,
        endExclusive: newlineIndex < 0 ? content.length : newlineIndex + 1,
        ...(newlineIndex < 0 ? {} : { lineEnding: hasCarriageReturn ? "\r\n" : "\n" }),
      });
    }
    if (newlineIndex < 0) break;
    lineStart = newlineIndex + 1;
  }
  return lines;
}

function preferredLineEnding(content: string): "\n" | "\r\n" {
  const newlineIndex = content.indexOf("\n");
  return newlineIndex > 0 && content[newlineIndex - 1] === "\r" ? "\r\n" : "\n";
}

function formatManagedBlockWithLineEnding(
  envConfig: EnvYaml,
  lineEnding: "\n" | "\r\n",
  trailingLineEnding: boolean,
): string {
  const normalized = formatOpenCodeEnvManagedBlock(envConfig).trimEnd();
  const formatted = lineEnding === "\n" ? normalized : normalized.replaceAll("\n", lineEnding);
  return trailingLineEnding ? `${formatted}${lineEnding}` : formatted;
}
