import type { EnvYaml } from "../../types.ts";

export const CODEX_ENV_MANAGED_BEGIN = "# BEGIN ai-share managed env";
export const CODEX_ENV_MANAGED_END = "# END ai-share managed env";

export function formatCodexEnvFile(envConfig: EnvYaml): string {
  return formatCodexEnvManagedBlock(envConfig);
}

export function formatCodexEnvManagedBlock(envConfig: EnvYaml): string {
  const variables = envConfig.variables;
  const lines = [
    CODEX_ENV_MANAGED_BEGIN,
    "# Non-secret Codex runtime environment only. Keep API keys and tokens outside this file.",
    ...Object.entries(variables).map(([key, value]) => `${key}=${formatEnvValue(value)}`),
    CODEX_ENV_MANAGED_END,
  ];
  return `${lines.join("\n")}\n`;
}

export function buildCodexEnvFileWithManagedBlock(envConfig: EnvYaml, existingContent?: string): string {
  const managedBlock = formatCodexEnvManagedBlock(envConfig).trimEnd();
  const normalizedExisting = existingContent?.replaceAll("\r\n", "\n");
  if (!normalizedExisting || isLegacyGeneratedEnvFile(normalizedExisting)) return `${managedBlock}\n`;

  const block = managedBlockLocation(normalizedExisting);
  if (block.status === "malformed") {
    throw new Error("Codex .env 中的 ai-share managed block marker 不完整或重复；请先手动修复 marker。");
  }
  if (block.status === "complete") {
    const afterEndIndex = block.endIndex + CODEX_ENV_MANAGED_END.length;
    return normalizeEnvFile(
      `${normalizedExisting.slice(0, block.beginIndex)}${managedBlock}${normalizedExisting.slice(afterEndIndex)}`,
    );
  }

  return normalizeEnvFile(`${normalizedExisting.trimEnd()}\n\n${managedBlock}\n`);
}

export function codexEnvManagedBlockIsCurrent(envConfig: EnvYaml, existingContent: string | undefined): boolean {
  if (!existingContent) return false;
  return (
    extractManagedBlock(existingContent.replaceAll("\r\n", "\n"))?.trimEnd() ===
    formatCodexEnvManagedBlock(envConfig).trimEnd()
  );
}

export function removeCodexEnvManagedBlock(existingContent: string): string {
  const normalized = existingContent.replaceAll("\r\n", "\n");
  const block = managedBlockLocation(normalized);
  if (block.status !== "complete") return normalizeEnvFile(normalized);
  return normalizeEnvFile(
    `${normalized.slice(0, block.beginIndex)}${normalized.slice(block.endIndex + CODEX_ENV_MANAGED_END.length)}`,
  );
}

export function codexEnvHasCompleteManagedBlock(existingContent: string): boolean {
  return managedBlockLocation(existingContent.replaceAll("\r\n", "\n")).status === "complete";
}

function formatEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:,@+\-=]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function isLegacyGeneratedEnvFile(content: string): boolean {
  return content.startsWith("# Generated by ai-share. Do not edit directly; change config/env.yaml instead.");
}

function extractManagedBlock(content: string): string | undefined {
  const block = managedBlockLocation(content);
  return block.status === "complete"
    ? content.slice(block.beginIndex, block.endIndex + CODEX_ENV_MANAGED_END.length)
    : undefined;
}

function managedBlockLocation(
  content: string,
): { status: "none" | "malformed" } | { status: "complete"; beginIndex: number; endIndex: number } {
  const beginIndexes = exactLineIndexes(content, CODEX_ENV_MANAGED_BEGIN);
  const endIndexes = exactLineIndexes(content, CODEX_ENV_MANAGED_END);
  if (beginIndexes.length === 0 && endIndexes.length === 0) return { status: "none" };
  const beginIndex = beginIndexes[0];
  const endIndex = endIndexes[0];
  if (beginIndexes.length !== 1 || endIndexes.length !== 1 || beginIndex === undefined || endIndex === undefined) {
    return { status: "malformed" };
  }
  if (endIndex < beginIndex) return { status: "malformed" };
  return { status: "complete", beginIndex, endIndex };
}

function exactLineIndexes(content: string, marker: string): number[] {
  const indexes: number[] = [];
  let lineStart = 0;
  while (lineStart <= content.length) {
    const newlineIndex = content.indexOf("\n", lineStart);
    const lineEnd = newlineIndex < 0 ? content.length : newlineIndex;
    if (content.slice(lineStart, lineEnd) === marker) indexes.push(lineStart);
    if (newlineIndex < 0) break;
    lineStart = newlineIndex + 1;
  }
  return indexes;
}

function normalizeEnvFile(content: string): string {
  return `${content.replaceAll("\r\n", "\n").trimEnd()}\n`;
}
