import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { ConfigSet } from "../validation.ts";
import {
  buildOpenCodeConfig,
  buildOpenCodeEnvFileWithManagedBlock,
  formatOpenCodeConfigJsonc,
  formatOpenCodeEnvFile,
  removeOpenCodeEnvManagedBlock,
} from "../../config-builders.ts";
import { parseYamlObject } from "../../yaml.ts";
import type { OpenCodeConfig } from "../../types.ts";

const projectRoot = resolve(import.meta.dir, "..", "..", "..");

describe("OpenCode generation contract", () => {
  test("formats one selected provider, all model aliases, agents and instructions", () => {
    const config = loadFixture();
    const output = formatOpenCodeConfigJsonc(
      buildOpenCodeConfig(config, "packyapi", ["/memory/policy.md", "/memory/user.yaml"], "/opencode/skills"),
    );
    expect(output).toStartWith("// Generated by ai-share.");
    const parsed = JSON.parse(output.slice(output.indexOf("{"))) as unknown as OpenCodeConfig;
    expect(parsed.model).toBe("packyapi/gpt-5.6-sol");
    expect(parsed.enabled_providers).toEqual(["packyapi"]);
    expect(parsed.instructions).toEqual(["/memory/policy.md", "/memory/user.yaml"]);
    expect(parsed.skills).toEqual({ paths: ["/opencode/skills"] });
    const provider = parsed.provider.packyapi;
    expect(provider).toBeDefined();
    if (!provider) throw new Error("packyapi provider is missing");
    expect(provider.name).toBe("Packy API");
    expect(provider.npm).toBe("@ai-sdk/openai-compatible");
    expect(provider.options).toEqual({
      baseURL: "https://www.packyapi.com/v1",
      apiKey: "{env:PACKYAPI_API_KEY}",
    });
    expect(provider.models["gpt-5.6-sol"]).toEqual({
      id: "gpt-5.6-sol",
      name: "gpt-5.6-sol",
      reasoning: true,
      options: { reasoningEffort: "high" },
    });
    expect(provider.models["gpt-5.6-coding"]).toEqual({
      id: "gpt-5.6-sol",
      name: "gpt-5.6-coding",
      reasoning: true,
      options: { reasoningEffort: "high" },
    });
    const agent = parsed.agent["ai-share-commit-operator"];
    expect(agent).toBeDefined();
    if (!agent) throw new Error("ai-share-commit-operator agent is missing");
    expect(agent.description).toBe("ai-share 的提交执行官");
    expect(agent.mode).toBe("subagent");
    expect(agent.model).toBe("packyapi/gpt-5.5");
    expect(agent.options).toEqual({ reasoningEffort: "low" });
    expect(agent.prompt).toContain("git status --short");
  });

  test("formats and updates the managed env block", () => {
    const env = { variables: { HTTP_PROXY: "http://127.0.0.1:7897" } };
    expect(formatOpenCodeEnvFile(env)).toContain("HTTP_PROXY=http://127.0.0.1:7897");
    const updated = buildOpenCodeEnvFileWithManagedBlock(env, "PRIVATE_FLAG=1\n");
    expect(updated).toContain("PRIVATE_FLAG=1");
    expect(removeOpenCodeEnvManagedBlock(updated)).toBe("PRIVATE_FLAG=1\n");
    expect(() => buildOpenCodeEnvFileWithManagedBlock(env, "# BEGIN ai-share managed env\nPRIVATE_FLAG=1\n")).toThrow(
      "managed block marker 不完整或重复",
    );
    const embeddedMarkers = 'PRIVATE_BEGIN="# BEGIN ai-share managed env"\nPRIVATE_END="# END ai-share managed env"\n';
    const withEmbeddedMarkers = buildOpenCodeEnvFileWithManagedBlock(env, embeddedMarkers);
    expect(withEmbeddedMarkers).toStartWith(embeddedMarkers);
    expect(removeOpenCodeEnvManagedBlock(withEmbeddedMarkers)).toBe(embeddedMarkers);
  });

  test("preserves bytes outside the managed env block during update and removal", () => {
    const env = { variables: { HTTP_PROXY: "http://127.0.0.1:7897" } };
    const prefix = "PRIVATE_FLAG=value with spaces  \r\n\r\n";
    const suffix = "AFTER_FLAG=keep trailing spaces  \r\n\r\n";
    const existing = `${prefix}# BEGIN ai-share managed env\r\nOLD=value\r\n# END ai-share managed env\r\n${suffix}`;

    const updated = buildOpenCodeEnvFileWithManagedBlock(env, existing);

    expect(updated.startsWith(prefix)).toBe(true);
    expect(updated.endsWith(suffix)).toBe(true);
    expect(updated).toContain(
      "# BEGIN ai-share managed env\r\n# Non-secret OpenCode runtime environment only. Keep API keys and tokens outside this file.\r\nHTTP_PROXY=http://127.0.0.1:7897\r\n# END ai-share managed env\r\n",
    );
    expect(removeOpenCodeEnvManagedBlock(updated)).toBe(`${prefix}${suffix}`);
  });

  test("maps stdio and HTTP MCP sources to OpenCode local and remote servers", () => {
    const config = loadFixture();
    config.mcp = {
      servers: {
        local: {
          transport: "stdio",
          command: "node",
          args: ["server.js"],
          env: { SERVICE_API_KEY: "${SERVICE_API_KEY}" },
        },
        remote: {
          transport: "http",
          url: "https://mcp.example.test",
          bearer_token_env_var: "MCP_TOKEN",
          oauth_client_id: "client-id",
        },
      },
    };
    const output = formatOpenCodeConfigJsonc(buildOpenCodeConfig(config, "packyapi", [], "/opencode/skills"));
    const parsed = JSON.parse(output.slice(output.indexOf("{"))) as { mcp: unknown };
    expect(parsed.mcp).toEqual({
      local: {
        type: "local",
        command: ["node", "server.js"],
        environment: { SERVICE_API_KEY: "{env:SERVICE_API_KEY}" },
      },
      remote: {
        type: "remote",
        url: "https://mcp.example.test",
        headers: { Authorization: "Bearer {env:MCP_TOKEN}" },
        oauth: { clientId: "client-id" },
      },
    });
  });
});

function loadFixture(): ConfigSet {
  return {
    global: loadYaml("global.yaml") as ConfigSet["global"],
    providers: loadYaml("provider.yaml") as ConfigSet["providers"],
    models: loadYaml("models.yaml") as ConfigSet["models"],
    mcp: loadYaml("mcp.yaml") as ConfigSet["mcp"],
    env: loadYaml("env.yaml") as ConfigSet["env"],
    agents: loadYaml("agents.yaml") as ConfigSet["agents"],
  };
}

function loadYaml(fileName: string): unknown {
  return parseYamlObject(readFileSync(resolve(projectRoot, "config", fileName), "utf8"));
}
