import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { ConfigSet } from "../validation.ts";
import {
  buildCodexAgentConfigs,
  buildCodexCliConfig,
  buildCodexEnvFileWithManagedBlock,
  formatCodexConfigToml,
  formatCodexAgentToml,
  formatCodexEnvFile,
  removeCodexEnvManagedBlock,
} from "../../config-builders.ts";
import { parseYamlObject } from "../../yaml.ts";

const projectRoot = resolve(import.meta.dir, "..", "..", "..");

describe("Codex generation contract", () => {
  test("formats one selected provider and the normalized model", () => {
    const config = loadFixture();
    const output = formatCodexConfigToml(buildCodexCliConfig(config, "packyapi", "/codex/AGENTS.md"));
    expect(output).toStartWith("# Generated by ai-share.");
    expect(output).toContain('model = "gpt-5.6-sol"');
    expect(output).toContain('model_provider = "packyapi"');
    expect(output).toContain('model_reasoning_effort = "high"');
    expect(output).toContain("[model_providers.packyapi]");
    expect(output).not.toContain("model_providers.codexapis");
    expect(() => Bun.TOML.parse(output)).not.toThrow();
  });

  test("formats a custom agent with an independent model and reasoning effort", () => {
    const config = loadFixture();
    config.global = { ...config.global, model: "gpt-5.6-sol" };
    const mainOutput = formatCodexConfigToml(buildCodexCliConfig(config, "codexapis", "/codex/AGENTS.md"));
    const agent = buildCodexAgentConfigs(config).commit;
    if (!agent) throw new Error("commit agent fixture is missing");
    const output = formatCodexAgentToml(agent);
    expect(mainOutput).toContain('model = "gpt-5.6-sol"');
    expect(mainOutput).toContain('model_reasoning_effort = "high"');
    expect(output).toStartWith("# Generated by ai-share.");
    expect(output).toContain('name = "commit"');
    expect(output).toContain('model = "gpt-5.5"');
    expect(output).toContain('model_reasoning_effort = "low"');
    expect(output).toContain('developer_instructions = "Inspect the diff.\\nCreate the requested commit.\\n');
    expect(output).toContain("git status --short");
    expect(output).toContain("git push --set-upstream origin HEAD");
    expect(output).toContain("Never use --no-verify, commit --amend, rebase, or force push");
    expect(() => Bun.TOML.parse(output)).not.toThrow();
  });

  test("formats and updates the managed env block", () => {
    const env = { variables: { HTTP_PROXY: "http://127.0.0.1:7897" } };
    expect(formatCodexEnvFile(env)).toContain("HTTP_PROXY=http://127.0.0.1:7897");
    const updated = buildCodexEnvFileWithManagedBlock(env, "PRIVATE_FLAG=1\n");
    expect(updated).toContain("PRIVATE_FLAG=1");
    expect(removeCodexEnvManagedBlock(updated)).toBe("PRIVATE_FLAG=1\n");
    expect(() => buildCodexEnvFileWithManagedBlock(env, "# BEGIN ai-share managed env\nPRIVATE_FLAG=1\n")).toThrow(
      "managed block marker 不完整或重复",
    );
    const embeddedMarkers = 'PRIVATE_BEGIN="# BEGIN ai-share managed env"\nPRIVATE_END="# END ai-share managed env"\n';
    const withEmbeddedMarkers = buildCodexEnvFileWithManagedBlock(env, embeddedMarkers);
    expect(withEmbeddedMarkers).toStartWith(embeddedMarkers);
    expect(removeCodexEnvManagedBlock(withEmbeddedMarkers)).toBe(embeddedMarkers);
  });
});

function loadFixture(): ConfigSet {
  return {
    global: loadYaml("global.yaml") as ConfigSet["global"],
    providers: loadYaml("provider.yaml") as ConfigSet["providers"],
    models: loadYaml("models.yaml") as ConfigSet["models"],
    mcp: loadYaml("mcp.yaml") as ConfigSet["mcp"],
    env: loadYaml("env.yaml") as ConfigSet["env"],
    agents: loadYaml("agents.yaml") as ConfigSet["agents"],
  };
}

function loadYaml(fileName: string): unknown {
  return parseYamlObject(readFileSync(resolve(projectRoot, "config", fileName), "utf8"));
}
