import type {
  McpServerSource,
  OpenCodeAgent,
  OpenCodeConfig,
  OpenCodeMcpServer,
  OpenCodeModel,
  OpenCodeProvider,
} from "../../types.ts";
import { envReferenceName, requireEnvReferenceName } from "../env-ref.ts";
import type { ConfigSet } from "../validation.ts";
import { requireString } from "../validation.ts";

export const OPENCODE_CONFIG_GENERATED_HEADER =
  "// Generated by ai-share. Do not edit directly; change config/*.yaml instead.";

export function buildOpenCodeConfig(
  config: ConfigSet,
  providerId: string,
  modelId: string,
  instructionPaths: readonly string[],
  skillsDir: string,
): OpenCodeConfig {
  validateSelectedModel(config, providerId, modelId);

  const mcp = buildOpenCodeMcpServers(config.mcp.servers);
  return {
    $schema: "https://opencode.ai/config.json",
    model: modelReference(providerId, modelId),
    instructions: [...instructionPaths],
    skills: { paths: [skillsDir] },
    provider: {
      [providerId]: buildOpenCodeProvider(config, providerId),
      ...buildAlwaysIncludedProviders(config, providerId),
    },
    agent: buildOpenCodeAgents(config, providerId),
    ...(config.plugins.plugins.length > 0 ? { plugin: [...config.plugins.plugins] } : {}),
    ...(Object.keys(mcp).length > 0 ? { mcp } : {}),
  };
}

export function formatOpenCodeConfigJsonc(config: OpenCodeConfig): string {
  return `${OPENCODE_CONFIG_GENERATED_HEADER}\n${JSON.stringify(config, null, 2)}\n`;
}

function buildOpenCodeProvider(config: ConfigSet, providerId: string): OpenCodeProvider {
  const provider = config.providers.providers[providerId];
  if (!provider) throw new Error(`提供商未定义：${providerId}`);
  const options = {
    baseURL: provider.base_url,
    apiKey: `{env:${requireEnvReferenceName(provider.api_key, `providers.${providerId}.api_key`)}}`,
  };
  if (provider.native) {
    return {
      whitelist: [...provider.models],
      options,
    };
  }
  return {
    ...(provider.name ? { name: provider.name } : {}),
    npm: "@ai-sdk/openai-compatible",
    options,
    models: Object.fromEntries(
      provider.models.map((modelId) => {
        const model = config.models[modelId];
        if (!model || !Object.hasOwn(config.models, modelId)) throw new Error(`模型未定义：${modelId}`);
        return [modelId, buildOpenCodeModel(modelId, model)];
      }),
    ),
  };
}

function buildAlwaysIncludedProviders(config: ConfigSet, selectedProviderId: string): Record<string, OpenCodeProvider> {
  return Object.fromEntries(
    Object.entries(config.providers.providers)
      .filter(([id, provider]) => provider.always_include === true && id !== selectedProviderId)
      .map(([id]) => [id, buildOpenCodeProvider(config, id)]),
  );
}

function buildOpenCodeModel(modelId: string, model: ConfigSet["models"][string]): OpenCodeModel {
  return {
    id: model.model_name,
    name: modelId,
    ...(model.reasoning_effort ? { reasoning: true, options: { reasoningEffort: model.reasoning_effort } } : {}),
    ...(model.attachment !== undefined ? { attachment: model.attachment } : {}),
    ...(model.modalities ? { modalities: model.modalities } : {}),
  };
}

function buildOpenCodeAgents(config: ConfigSet, providerId: string): Record<string, OpenCodeAgent> {
  return Object.fromEntries(
    Object.entries(config.agents.agents).map(([agentId, source]) => {
      if (source.model && !source.model.includes("/") && !isProviderModel(config, providerId, source.model)) {
        throw new Error(`agent '${agentId}' 引用未关联提供商模型 '${providerId}/${source.model}'`);
      }
      return [
        agentId,
        {
          description: source.description,
          mode: source.mode,
          prompt: source.prompt,
          ...(source.model
            ? { model: source.model.includes("/") ? source.model : modelReference(providerId, source.model) }
            : {}),
          ...(source.reasoning_effort ? { options: { reasoningEffort: source.reasoning_effort } } : {}),
        },
      ];
    }),
  );
}

function validateSelectedModel(config: ConfigSet, providerId: string, modelId: string): void {
  const provider = config.providers.providers[providerId];
  if (!provider || !Object.hasOwn(config.providers.providers, providerId)) {
    throw new Error(`提供商未定义：${providerId}`);
  }
  if (!Object.hasOwn(config.models, modelId)) throw new Error(`模型未定义：${modelId}`);
  if (!provider.models.includes(modelId)) throw new Error(`模型未关联提供商：${providerId}/${modelId}`);
}

function isProviderModel(config: ConfigSet, providerId: string, modelId: string): boolean {
  const provider = config.providers.providers[providerId];
  return Boolean(
    provider &&
    Object.hasOwn(config.providers.providers, providerId) &&
    Object.hasOwn(config.models, modelId) &&
    provider.models.includes(modelId),
  );
}

function buildOpenCodeMcpServers(servers: Record<string, McpServerSource>): Record<string, OpenCodeMcpServer> {
  return Object.fromEntries(
    Object.entries(servers).map(([serverId, server]) => [serverId, buildOpenCodeMcpServer(serverId, server)]),
  );
}

function buildOpenCodeMcpServer(serverId: string, server: McpServerSource): OpenCodeMcpServer {
  if (server.transport === "http" || server.url) {
    return {
      type: "remote",
      url: requireString(server.url, `mcp.servers.${serverId}.url`),
      ...(server.bearer_token_env_var
        ? { headers: { Authorization: `Bearer {env:${server.bearer_token_env_var}}` } }
        : {}),
      ...(server.oauth_client_id ? { oauth: { clientId: server.oauth_client_id } } : {}),
    };
  }

  return {
    type: "local",
    command: [requireString(server.command, `mcp.servers.${serverId}.command`), ...(server.args ?? [])],
    ...(server.env ? { environment: buildOpenCodeMcpEnvironment(server.env) } : {}),
  };
}

function buildOpenCodeMcpEnvironment(environment: Record<string, string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(environment).map(([name, value]) => {
      const envName = envReferenceName(value);
      return [name, envName ? `{env:${envName}}` : value];
    }),
  );
}

function modelReference(providerId: string, modelId: string): string {
  return `${providerId}/${modelId}`;
}
