import type { WezTermConfig } from "../../types.ts";

export const WEZTERM_CONFIG_MANAGED_HEADER =
  "-- Generated by ai-share. Do not edit directly; change config/wezterm.yaml instead.\n";

export function buildWezTermLua(config: WezTermConfig): string {
  const lines = [
    WEZTERM_CONFIG_MANAGED_HEADER.trimEnd(),
    'local wezterm = require("wezterm")',
    "",
    "local config = wezterm.config_builder()",
    "",
  ];

  const colorScheme = themeName(config.color_scheme);
  if (colorScheme) lines.push(`config.color_scheme = "${colorScheme}"`);
  lines.push(
    `config.font_size = ${config.font_size}`,
    `config.window_background_opacity = ${config.window_background_opacity}`,
    `config.scrollback_lines = ${config.scrollback_lines}`,
    `config.exit_behavior = "${exitBehaviorName(config.exit_behavior)}"`,
  );

  if (config.shell === "platform-native") {
    lines.push(
      "",
      'if wezterm.target_triple == "x86_64-pc-windows-msvc" then',
      '  config.default_prog = { "pwsh.exe", "-NoLogo" }',
      'elseif wezterm.target_triple:match("-apple-darwin$") then',
      '  config.default_prog = { "/bin/zsh", "-l" }',
      "end",
    );
  }

  if (config.maximize_on_startup) {
    lines.push(
      "",
      'wezterm.on("gui-startup", function(cmd)',
      "  local _, _, window = wezterm.mux.spawn_window(cmd or {})",
      "  window:gui_window():maximize()",
      "end)",
    );
  }

  lines.push("", "return config");
  return `${lines.join("\n")}\n`;
}

function themeName(colorScheme: WezTermConfig["color_scheme"]): string | undefined {
  switch (colorScheme) {
    case "catppuccin-mocha":
      return "Catppuccin Mocha";
    case "dracula":
      return "Dracula";
    case "tokyo-night":
      return "Tokyo Night";
    case "wezterm-default":
      return undefined;
  }
}

function exitBehaviorName(exitBehavior: WezTermConfig["exit_behavior"]): string {
  switch (exitBehavior) {
    case "hold":
      return "Hold";
    case "close":
      return "Close";
    case "close-on-clean-exit":
      return "CloseOnCleanExit";
  }
}
