import { describe, expect, test } from "bun:test";
import type { WezTermConfig } from "../../types.ts";
import { WEZTERM_CONFIG_MANAGED_HEADER, buildWezTermLua } from "./wezterm.ts";

const defaults: WezTermConfig = {
  shell: "platform-native",
  color_scheme: "catppuccin-mocha",
  font_size: 12,
  window_background_opacity: 0.94,
  maximize_on_startup: false,
  scrollback_lines: 100000,
};

describe("WezTerm Lua generation", () => {
  test("starts with the stable managed header and config builder", () => {
    expect(WEZTERM_CONFIG_MANAGED_HEADER).toBe(
      "-- Generated by ai-share. Do not edit directly; change config/wezterm.yaml instead.\n",
    );
    expect(buildWezTermLua(defaults)).toStartWith(
      `${WEZTERM_CONFIG_MANAGED_HEADER}local wezterm = require("wezterm")\n\nlocal config = wezterm.config_builder()\n`,
    );
  });

  test.each([
    ["catppuccin-mocha", "Catppuccin Mocha"],
    ["dracula", "Dracula"],
    ["tokyo-night", "Tokyo Night"],
  ] as const)("maps the %s theme to %s", (colorScheme, weztermName) => {
    const output = buildWezTermLua({ ...defaults, color_scheme: colorScheme });

    expect(output).toContain(`config.color_scheme = "${weztermName}"\n`);
  });

  test("omits color_scheme for the WezTerm default theme", () => {
    const output = buildWezTermLua({ ...defaults, color_scheme: "wezterm-default" });

    expect(output).not.toContain("color_scheme");
  });

  test("selects PowerShell and zsh from wezterm.target_triple for the platform-native shell", () => {
    const output = buildWezTermLua(defaults);

    expect(output).toContain(
      'if wezterm.target_triple == "x86_64-pc-windows-msvc" then\n' +
        '  config.default_prog = { "pwsh.exe", "-NoLogo" }\n' +
        'elseif wezterm.target_triple:match("-apple-darwin$") then\n' +
        '  config.default_prog = { "/bin/zsh", "-l" }\n' +
        "end\n",
    );
  });

  test("omits default_prog and platform detection for the WezTerm default shell", () => {
    const output = buildWezTermLua({ ...defaults, shell: "wezterm-default" });

    expect(output).not.toContain("default_prog");
    expect(output).not.toContain("target_triple");
  });

  test("emits all numeric options without locale-dependent formatting", () => {
    const output = buildWezTermLua({
      ...defaults,
      font_size: 13,
      window_background_opacity: 0.88,
      scrollback_lines: 1000000,
    });

    expect(output).toContain(
      "config.font_size = 13\n" + "config.window_background_opacity = 0.88\n" + "config.scrollback_lines = 1000000\n",
    );
  });

  test("emits the documented gui-startup maximization flow only when enabled", () => {
    const maximized = buildWezTermLua({ ...defaults, maximize_on_startup: true });

    expect(maximized).toContain(
      'wezterm.on("gui-startup", function(cmd)\n' +
        "  local _, _, window = wezterm.mux.spawn_window(cmd or {})\n" +
        "  window:gui_window():maximize()\n" +
        "end)\n",
    );
    expect(buildWezTermLua(defaults)).not.toContain("wezterm.on");
  });

  test("is deterministic and uses LF with exactly one trailing newline", () => {
    const first = buildWezTermLua(defaults);
    const second = buildWezTermLua({ ...defaults });

    expect(second).toBe(first);
    expect(first).not.toContain("\r");
    expect(first.endsWith("\n")).toBe(true);
    expect(first.endsWith("\n\n")).toBe(false);
  });
});
