import { describe, expect, test } from "bun:test";
import { resolve } from "node:path";
import { buildAiocLauncherFiles } from "./aioc-install.ts";
import type { GeneratorPaths } from "./paths.ts";

describe("aioc install files", () => {
  test("builds standalone Bun and cross-platform wrappers for the declared targets", () => {
    const paths = fixturePaths();
    const files = buildAiocLauncherFiles(paths);
    expect(Object.keys(files).sort()).toEqual(
      [paths.targetAiocScript, paths.targetAiocUnix, paths.targetAiocCmd, paths.targetAiocPowerShell].sort(),
    );
    expect(files[paths.targetAiocScript]).toContain("Generated by ai-share OpenCode launcher.");
    expect(files[paths.targetAiocUnix]).toContain('exec bun "$(dirname "$0")/aioc.ts" "$@"');
    expect(files[paths.targetAiocCmd]).toContain('@bun "%~dp0aioc.ts" %*');
    expect(files[paths.targetAiocPowerShell]).toContain("$PSScriptRoot");
  });
});

function fixturePaths(): GeneratorPaths {
  const home = resolve("fixture-home");
  const config = resolve(home, ".config", "opencode");
  const bin = resolve(home, ".local", "bin");
  return {
    projectRoot: resolve("fixture-project"),
    configDir: resolve("fixture-project", "config"),
    homeDir: home,
    targetOpenCodeConfigDir: config,
    targetOpenCodeConfig: resolve(config, "opencode.jsonc"),
    targetOpenCodeEnv: resolve(config, ".env"),
    targetOpenCodeSkillsDir: resolve(config, "skills"),
    targetUserBinDir: bin,
    targetAiocScript: resolve(bin, "aioc.ts"),
    targetAiocUnix: resolve(bin, "aioc"),
    targetAiocCmd: resolve(bin, "aioc.cmd"),
    targetAiocPowerShell: resolve(bin, "aioc.ps1"),
  };
}
