import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { ArchifyYaml } from "../types.ts";
import { ARCHIFY_REF_FILE } from "./archify-ownership.ts";
import { buildGenerationPlan, SKILL_MANAGED_CONTENT, SKILL_MANAGED_MARKER } from "./generation-plan.ts";
import { buildGeneratorPaths } from "./paths.ts";

const config: ArchifyYaml = {
  archify: {
    repo: "tt-a1i/archify",
    skill: "archify",
    ref: "cffdd42eed0ebf013aa070378d94facdd3d56b10",
    enabled: true,
  },
};

function createRoot(prefix: string): string {
  return mkdtempSync(join(tmpdir(), prefix));
}

function planInput(root: string, archify: ArchifyYaml = config) {
  const paths = buildGeneratorPaths(root, { HOME: join(root, "home"), OPENCODE_CONFIG_DIR: join(root, "opencode") });
  return {
    paths,
    configJsonc: "// Generated by ai-share. Do not edit directly; change config/*.yaml instead.\n{}\n",
    envConfig: { variables: {} },
    launcherFiles: {},
    force: false,
    skillNames: new Set<string>(),
    archify,
  };
}

describe("Archify ownership planning", () => {
  test("reports an enabled but not installed external skill without creating network content", async () => {
    const root = createRoot("ai-share-archify-plan-missing-");
    try {
      const plan = await buildGenerationPlan(planInput(root));
      expect(plan.preserved).toContainEqual({
        path: join(root, "home", ".agents", "skills", "archify"),
        reason: "archify-not-installed",
        ownership: "missing",
      });
      expect(plan.actions.some((action) => action.path === join(root, "home", ".agents", "skills", "archify"))).toBe(
        false,
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("preserves a managed skill only when its pinned ownership record matches", async () => {
    const root = createRoot("ai-share-archify-plan-current-");
    try {
      const skillDir = join(root, "home", ".agents", "skills", "archify");
      mkdirSync(skillDir, { recursive: true });
      writeFileSync(join(skillDir, "SKILL.md"), "# Archify\n", "utf8");
      writeFileSync(join(skillDir, SKILL_MANAGED_MARKER), SKILL_MANAGED_CONTENT, "utf8");
      writeFileSync(join(skillDir, ARCHIFY_REF_FILE), `${JSON.stringify(config.archify)}\n`, "utf8");

      const plan = await buildGenerationPlan(planInput(root));
      expect(plan.collisions).toEqual([]);
      expect(plan.preserved).toContainEqual({
        path: join(skillDir, ARCHIFY_REF_FILE),
        reason: "content-current",
        ownership: "managed",
      });
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("blocks a managed skill whose recorded revision drifts", async () => {
    const root = createRoot("ai-share-archify-plan-drift-");
    try {
      const skillDir = join(root, "home", ".agents", "skills", "archify");
      mkdirSync(skillDir, { recursive: true });
      writeFileSync(join(skillDir, "SKILL.md"), "# Archify\n", "utf8");
      writeFileSync(join(skillDir, SKILL_MANAGED_MARKER), SKILL_MANAGED_CONTENT, "utf8");
      writeFileSync(
        join(skillDir, ARCHIFY_REF_FILE),
        `${JSON.stringify({ ...config.archify, ref: "1111111111111111111111111111111111111111" })}\n`,
        "utf8",
      );

      const plan = await buildGenerationPlan(planInput(root));
      expect(plan.collisions).toContainEqual({
        path: join(skillDir, ARCHIFY_REF_FILE),
        reason: "archify-ref-drift",
        ownership: "managed",
      });
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("deletes a managed Archify directory when disabled", async () => {
    const root = createRoot("ai-share-archify-plan-disabled-");
    try {
      const skillDir = join(root, "home", ".agents", "skills", "archify");
      mkdirSync(skillDir, { recursive: true });
      writeFileSync(join(skillDir, "SKILL.md"), "# Archify\n", "utf8");
      writeFileSync(join(skillDir, SKILL_MANAGED_MARKER), SKILL_MANAGED_CONTENT, "utf8");
      writeFileSync(join(skillDir, ARCHIFY_REF_FILE), `${JSON.stringify(config.archify)}\n`, "utf8");

      const plan = await buildGenerationPlan(planInput(root, { archify: { ...config.archify, enabled: false } }));
      expect(plan.actions).toContainEqual({
        kind: "delete",
        path: skillDir,
        reason: "stale-managed-skill",
        ownership: "managed",
      });
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
