import type { Stats } from "node:fs";
import { lstat, readFile, readdir } from "node:fs/promises";
import { basename, resolve } from "node:path";
import type { ArchifyYaml, EnvYaml } from "../types.ts";
import { OPENCODE_CONFIG_GENERATED_HEADER } from "../config/builders/opencode.ts";
import { buildOpenCodeEnvFileWithManagedBlock } from "../config/builders/env.ts";
import { ARCHIFY_REF_FILE } from "./archify-ownership.ts";
import { NATIVE_SKILLS } from "./native-skills.ts";
import { pathExists, StagedFileWriter } from "./fs.ts";
import type { GeneratorPaths } from "./paths.ts";

export const GENERATED_CONFIG_HEADER: string = OPENCODE_CONFIG_GENERATED_HEADER;
export const SKILL_MANAGED_MARKER = ".ai-share-managed";
export const SKILL_MANAGED_CONTENT = "ai-share\n";
export const LAUNCHER_MANAGED_MARKER = "Generated by ai-share OpenCode launcher.";

export type PlanOwnership = "missing" | "managed" | "unmanaged" | "invalid-marker";

export type PlanReason =
  | "target-missing"
  | "content-current"
  | "managed-content-drift"
  | "managed-mode-drift"
  | "env-managed-block-drift"
  | "force-adoption"
  | "unowned-collision"
  | "blocking-path-collision"
  | "force-replace-blocking-path"
  | "stale-managed-skill"
  | "unmanaged-skill-preserved"
  | "invalid-marker-preserved"
  | "archify-not-installed"
  | "archify-ref-drift"
  | "archify-content-missing";

export type PlannedPath = {
  path: string;
  reason: PlanReason;
  ownership: PlanOwnership;
};

export type GenerationAction =
  | (PlannedPath & { kind: "create" | "update"; content: string; executable?: boolean })
  | (PlannedPath & { kind: "delete" });

export type GenerationPlan = {
  actions: GenerationAction[];
  preserved: PlannedPath[];
  collisions: PlannedPath[];
};

export async function buildGenerationPlan(input: {
  paths: GeneratorPaths;
  configJsonc: string;
  envConfig: EnvYaml;
  launcherFiles: Readonly<Record<string, string>>;
  force: boolean;
  platform?: NodeJS.Platform;
  skillNames?: ReadonlySet<string>;
  archify?: ArchifyYaml;
}): Promise<GenerationPlan> {
  const plan: GenerationPlan = { actions: [], preserved: [], collisions: [] };

  await planOwnedFile(
    plan,
    input.paths.targetOpenCodeConfig,
    input.configJsonc,
    (content) => content.startsWith(GENERATED_CONFIG_HEADER),
    input.force,
  );
  await planManagedEnv(plan, input.paths.targetOpenCodeEnv, input.envConfig);
  await planSkills(
    plan,
    input.paths.targetOpenCodeSkillsDir,
    input.force,
    input.skillNames ?? new Set(NATIVE_SKILLS.map((skill) => skill.name)),
  );
  if (input.archify) {
    await planArchifySkill(plan, input.paths.targetGlobalSkillsDir, input.archify);
  }
  await planLaunchers(plan, input.paths, input.launcherFiles, input.force, input.platform ?? process.platform);
  return plan;
}

async function planManagedEnv(plan: GenerationPlan, path: string, envConfig: EnvYaml): Promise<void> {
  const stat = await lstatIfExists(path);
  if (stat && (!stat.isFile() || stat.isSymbolicLink())) {
    plan.collisions.push(plannedPath(path, "blocking-path-collision", "unmanaged"));
    return;
  }
  const existing = stat ? await readFile(path, "utf8") : undefined;
  planWriteIfChanged(plan, path, buildOpenCodeEnvFileWithManagedBlock(envConfig, existing), existing, {
    changedReason: "env-managed-block-drift",
    ownership: "managed",
  });
}

async function planLaunchers(
  plan: GenerationPlan,
  paths: GeneratorPaths,
  launcherFiles: Readonly<Record<string, string>>,
  force: boolean,
  platform: NodeJS.Platform,
): Promise<void> {
  const allowed = new Set(
    [paths.targetAiocScript, paths.targetAiocUnix, paths.targetAiocCmd, paths.targetAiocPowerShell].map((path) =>
      resolve(path),
    ),
  );
  for (const [path, content] of Object.entries(launcherFiles)) {
    const target = resolve(path);
    if (!allowed.has(target)) throw new Error(`aioc 输出路径不受支持：${path}`);
    await planOwnedFile(
      plan,
      target,
      content,
      (existing) => hasManagedLauncherHeader(target, existing, paths),
      force,
      target === resolve(paths.targetAiocUnix),
      platform,
    );
  }
}

export function hasManagedLauncherHeader(path: string, content: string, paths: GeneratorPaths): boolean {
  const target = resolve(path);
  const lines = content.replaceAll("\r\n", "\n").split("\n");
  if (target === resolve(paths.targetAiocScript)) {
    return lines[0] === "#!/usr/bin/env bun" && lines[1] === `// ${LAUNCHER_MANAGED_MARKER}`;
  }
  if (target === resolve(paths.targetAiocUnix)) {
    return lines[0] === "#!/bin/sh" && lines[1] === `# ${LAUNCHER_MANAGED_MARKER}`;
  }
  if (target === resolve(paths.targetAiocCmd)) return lines[0] === `@REM ${LAUNCHER_MANAGED_MARKER}`;
  if (target === resolve(paths.targetAiocPowerShell)) return lines[0] === `# ${LAUNCHER_MANAGED_MARKER}`;
  return false;
}

async function planSkills(
  plan: GenerationPlan,
  skillsDir: string,
  force: boolean,
  enabledSkillNames: ReadonlySet<string>,
): Promise<void> {
  const enabledSkills = NATIVE_SKILLS.filter((skill) => enabledSkillNames.has(skill.name));
  const currentSkillNames = new Set(enabledSkills.map((skill) => skill.name));
  for (const skill of enabledSkills) {
    const skillDir = resolve(skillsDir, skill.name);
    const markerPath = resolve(skillDir, SKILL_MANAGED_MARKER);
    const skillPath = resolve(skillDir, "SKILL.md");
    const directoryStat = await lstatIfExists(skillDir);
    const directoryExists = directoryStat !== undefined;
    if (directoryStat && (!directoryStat.isDirectory() || directoryStat.isSymbolicLink())) {
      if (!force) {
        plan.collisions.push(plannedPath(skillDir, "blocking-path-collision", "unmanaged"));
        continue;
      }
      plan.actions.push({
        kind: "delete",
        path: skillDir,
        reason: "force-replace-blocking-path",
        ownership: "unmanaged",
      });
      planWriteIfChanged(plan, skillPath, skill.content, undefined, {
        changedReason: "force-adoption",
        ownership: "unmanaged",
        missingReason: "force-adoption",
        missingOwnership: "unmanaged",
      });
      planWriteIfChanged(plan, markerPath, SKILL_MANAGED_CONTENT, undefined, {
        changedReason: "force-adoption",
        ownership: "unmanaged",
        missingReason: "force-adoption",
        missingOwnership: "unmanaged",
      });
      continue;
    }

    const ownership = directoryExists ? await skillMarkerOwnership(skillDir) : "unmanaged";
    const owned = ownership === "managed";
    if (directoryExists && !owned && !force) {
      plan.collisions.push(plannedPath(skillDir, "unowned-collision", ownership));
      continue;
    }
    const existingSkill = (await pathExists(skillPath)) ? await readFile(skillPath, "utf8") : undefined;
    const existingMarker = (await pathExists(markerPath)) ? await readFile(markerPath, "utf8") : undefined;
    const context = directoryExists
      ? skillWriteContext(ownership, force)
      : { changedReason: "managed-content-drift" as const, ownership: "missing" as const };
    planWriteIfChanged(plan, skillPath, skill.content, existingSkill, context);
    planWriteIfChanged(plan, markerPath, SKILL_MANAGED_CONTENT, existingMarker, context);
  }

  const stale = await classifyStaleSkillDirs(skillsDir, currentSkillNames);
  for (const skill of stale.deletes) plan.actions.push({ kind: "delete", ...skill });
  plan.preserved.push(...stale.preserved);
}

async function planArchifySkill(plan: GenerationPlan, skillsDir: string, config: ArchifyYaml): Promise<void> {
  const { repo, skill, ref, enabled } = config.archify;
  const skillDir = resolve(skillsDir, skill);
  const markerPath = resolve(skillDir, SKILL_MANAGED_MARKER);
  const refPath = resolve(skillDir, ARCHIFY_REF_FILE);
  const directoryStat = await lstatIfExists(skillDir);

  if (!directoryStat) {
    if (enabled) plan.preserved.push(plannedPath(skillDir, "archify-not-installed", "missing"));
    return;
  }
  if (!directoryStat.isDirectory() || directoryStat.isSymbolicLink()) {
    plan.collisions.push(plannedPath(skillDir, "blocking-path-collision", "unmanaged"));
    return;
  }

  const ownership = await readArchifyOwnership(skillDir);
  if (ownership.kind !== "managed") {
    if (enabled) plan.collisions.push(plannedPath(skillDir, "unowned-collision", ownership.kind));
    else plan.preserved.push(plannedPath(skillDir, "unmanaged-skill-preserved", ownership.kind));
    return;
  }

  if (!enabled) {
    plan.actions.push({ kind: "delete", path: skillDir, reason: "stale-managed-skill", ownership: "managed" });
    return;
  }

  if (ownership.record.repo !== repo || ownership.record.skill !== skill || ownership.record.ref !== ref) {
    plan.collisions.push(plannedPath(refPath, "archify-ref-drift", "managed"));
    return;
  }
  if (!(await pathExists(resolve(skillDir, "SKILL.md")))) {
    plan.collisions.push(plannedPath(skillDir, "archify-content-missing", "managed"));
    return;
  }
  plan.preserved.push(plannedPath(markerPath, "content-current", "managed"));
  plan.preserved.push(plannedPath(refPath, "content-current", "managed"));
}

export async function executeGenerationPlan(plan: GenerationPlan, stagingRoot: string): Promise<void> {
  if (plan.collisions.length > 0) {
    throw new Error(
      `检测到未由 ai-share 管理的目标，未写入任何文件：\n${plan.collisions.map((entry) => `- ${entry.path}`).join("\n")}\n请先备份现有文件；如确认接管，请使用 --force。`,
    );
  }
  if (plan.actions.length === 0) return;
  const writer = await StagedFileWriter.create(stagingRoot);
  try {
    for (const action of plan.actions) {
      if (action.kind === "delete") writer.delete(action.path);
      else await writer.writeText(action.path, action.content, action.executable ? 0o755 : undefined);
    }
    await writer.promote();
  } catch (error) {
    await writer.cleanup();
    throw error;
  }
}

async function planOwnedFile(
  plan: GenerationPlan,
  path: string,
  content: string,
  isOwnedContent: (content: string) => boolean,
  force: boolean,
  executable = false,
  platform: NodeJS.Platform = process.platform,
): Promise<void> {
  const stat = await lstatIfExists(path);
  if (!stat) {
    plan.actions.push({
      kind: "create",
      path,
      content,
      reason: "target-missing",
      ownership: "missing",
      ...(executable ? { executable: true } : {}),
    });
    return;
  }
  if (!stat.isFile() || stat.isSymbolicLink()) {
    if (!force) {
      plan.collisions.push(plannedPath(path, "blocking-path-collision", "unmanaged"));
      return;
    }
    plan.actions.push({
      kind: "update",
      path,
      content,
      reason: "force-replace-blocking-path",
      ownership: "unmanaged",
      ...(executable ? { executable: true } : {}),
    });
    return;
  }
  const existing = await readFile(path, "utf8");
  if (existing === content) {
    if (executable && platform !== "win32" && (stat.mode & 0o111) === 0) {
      plan.actions.push({
        kind: "update",
        path,
        content,
        reason: "managed-mode-drift",
        ownership: "managed",
        executable: true,
      });
    } else {
      plan.preserved.push(plannedPath(path, "content-current", "managed"));
    }
  } else if (isOwnedContent(existing)) {
    plan.actions.push({
      kind: "update",
      path,
      content,
      reason: "managed-content-drift",
      ownership: "managed",
      ...(executable ? { executable: true } : {}),
    });
  } else if (force) {
    plan.actions.push({
      kind: "update",
      path,
      content,
      reason: "force-adoption",
      ownership: "unmanaged",
      ...(executable ? { executable: true } : {}),
    });
  } else {
    plan.collisions.push(plannedPath(path, "unowned-collision", "unmanaged"));
  }
}

function planWriteIfChanged(
  plan: GenerationPlan,
  path: string,
  content: string,
  existing: string | undefined,
  context: {
    changedReason: PlanReason;
    ownership: PlanOwnership;
    missingReason?: PlanReason;
    missingOwnership?: PlanOwnership;
  },
): void {
  if (existing === content) {
    plan.preserved.push(plannedPath(path, "content-current", context.ownership));
  } else if (existing === undefined) {
    plan.actions.push({
      kind: "create",
      path,
      content,
      reason: context.missingReason ?? "target-missing",
      ownership: context.missingOwnership ?? "missing",
    });
  } else {
    plan.actions.push({
      kind: "update",
      path,
      content,
      reason: context.changedReason,
      ownership: context.ownership,
    });
  }
}

async function classifyStaleSkillDirs(
  skillsDir: string,
  currentSkillNames: ReadonlySet<string>,
): Promise<{ deletes: PlannedPath[]; preserved: PlannedPath[] }> {
  if (!(await pathExists(skillsDir))) return { deletes: [], preserved: [] };
  const deletes: PlannedPath[] = [];
  const preserved: PlannedPath[] = [];
  for (const entry of await readdir(skillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || currentSkillNames.has(entry.name)) continue;
    const skillDir = resolve(skillsDir, entry.name);
    const ownership = await skillMarkerOwnership(skillDir);
    if (ownership === "managed") {
      deletes.push(plannedPath(skillDir, "stale-managed-skill", ownership));
    } else if (ownership === "invalid-marker") {
      preserved.push(plannedPath(skillDir, "invalid-marker-preserved", ownership));
    } else {
      preserved.push(plannedPath(skillDir, "unmanaged-skill-preserved", ownership));
    }
  }
  const byName = (left: PlannedPath, right: PlannedPath): number =>
    basename(left.path).localeCompare(basename(right.path));
  return { deletes: deletes.sort(byName), preserved: preserved.sort(byName) };
}

export async function hasManagedSkillMarker(skillDir: string): Promise<boolean> {
  return (await skillMarkerOwnership(skillDir)) === "managed";
}

type ArchifyOwnership =
  | { kind: "managed"; record: { repo: string; skill: string; ref: string } }
  | { kind: "unmanaged" | "invalid-marker" };

async function readArchifyOwnership(skillDir: string): Promise<ArchifyOwnership> {
  const markerOwnership = await skillMarkerOwnership(skillDir);
  if (markerOwnership !== "managed") return { kind: markerOwnership };
  const refPath = resolve(skillDir, ARCHIFY_REF_FILE);
  const refStat = await lstatIfExists(refPath);
  if (!refStat || !refStat.isFile() || refStat.isSymbolicLink()) return { kind: "invalid-marker" };
  try {
    const value: unknown = JSON.parse(await readFile(refPath, "utf8"));
    if (!isArchifyOwnershipRecord(value)) return { kind: "invalid-marker" };
    return { kind: "managed", record: value };
  } catch {
    return { kind: "invalid-marker" };
  }
}

function isArchifyOwnershipRecord(value: unknown): value is { repo: string; skill: string; ref: string } {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const record = value as Record<string, unknown>;
  return (
    typeof record.repo === "string" &&
    typeof record.skill === "string" &&
    typeof record.ref === "string" &&
    record.repo.length > 0 &&
    record.skill.length > 0 &&
    record.ref.length > 0
  );
}

async function skillMarkerOwnership(skillDir: string): Promise<"managed" | "unmanaged" | "invalid-marker"> {
  const markerPath = resolve(skillDir, SKILL_MANAGED_MARKER);
  const stat = await lstatIfExists(markerPath);
  if (!stat) return "unmanaged";
  if (!stat.isFile() || stat.isSymbolicLink()) return "invalid-marker";
  return (await readFile(markerPath, "utf8")) === SKILL_MANAGED_CONTENT ? "managed" : "invalid-marker";
}

function skillWriteContext(
  ownership: PlanOwnership,
  force: boolean,
): {
  changedReason: PlanReason;
  ownership: PlanOwnership;
  missingReason?: PlanReason;
  missingOwnership?: PlanOwnership;
} {
  if (force && (ownership === "unmanaged" || ownership === "invalid-marker")) {
    return {
      changedReason: "force-adoption",
      ownership,
      missingReason: "force-adoption",
      missingOwnership: ownership,
    };
  }
  return { changedReason: "managed-content-drift", ownership };
}

async function lstatIfExists(path: string): Promise<Stats | undefined> {
  try {
    return await lstat(path);
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") return undefined;
    throw error;
  }
}

function plannedPath(path: string, reason: PlanReason, ownership: PlanOwnership): PlannedPath {
  return { path, reason, ownership };
}
