import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { nativeSkillNames } from "./native-skills.ts";
import { buildGenerationPlan, SKILL_MANAGED_CONTENT, SKILL_MANAGED_MARKER } from "./generation-plan.ts";
import { buildGeneratorPaths } from "./paths.ts";

describe("buildGenerationPlan skillNames", () => {
  test("excludes disabled skills from writes and deletes stale managed dirs", async () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-skill-filter-"));
    try {
      const all = nativeSkillNames();
      const disabled = all[0];
      const enabled = new Set(all.slice(1));
      const openCodeDir = join(root, "opencode");
      const markerPath = join(openCodeDir, "skills", disabled ?? "unused", SKILL_MANAGED_MARKER);
      mkdirSync(dirname(markerPath), { recursive: true });
      writeFileSync(markerPath, SKILL_MANAGED_CONTENT, "utf8");
      const paths = buildGeneratorPaths(root, { HOME: join(root, "home"), OPENCODE_CONFIG_DIR: openCodeDir });
      const plan = await buildGenerationPlan({
        paths,
        configJsonc: "// Generated by ai-share. Do not edit directly; change config/*.yaml instead.\n{}\n",
        envConfig: { variables: {} },
        launcherFiles: {},
        force: false,
        skillNames: enabled,
      });
      expect(plan.actions.some((action) => action.kind === "delete" && action.reason === "stale-managed-skill")).toBe(
        true,
      );
      for (const name of enabled) {
        expect(
          plan.actions.some(
            (action) => action.path === join(openCodeDir, "skills", name, "SKILL.md") && action.kind === "create",
          ),
        ).toBe(true);
      }
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
