import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SUPERPOWERS_PLUGIN_SPEC } from "./install-plan.ts";
import { buildGeneratorPaths } from "./paths.ts";
import { SKILL_MANAGED_CONTENT, SKILL_MANAGED_MARKER } from "./generation-plan.ts";
import {
  buildOptionalComponentChoices,
  parseOptionalSelection,
  readTargetOptionalState,
  type OptionalComponentState,
} from "./optional-components.ts";

describe("optional components", () => {
  test("builds choices for tool, agents, and skills with target state", () => {
    const state: OptionalComponentState = {
      superpowers: true,
      agents: new Set(["ai-sensei"]),
      skills: new Set(["memory-curator"]),
    };
    const choices = buildOptionalComponentChoices({
      agentIds: ["ai-sensei", "ai-share-commit-operator"],
      skillNames: ["memory-curator", "failure-distiller"],
      state,
    });
    expect(choices).toEqual([
      {
        id: SUPERPOWERS_PLUGIN_SPEC,
        label: "Superpowers",
        kind: "tool",
        required: false,
        selected: true,
        status: "已启用",
      },
      { id: "ai-sensei", label: "ai-sensei", kind: "agent", required: false, selected: true, status: "已启用" },
      {
        id: "ai-share-commit-operator",
        label: "ai-share-commit-operator",
        kind: "agent",
        required: false,
        selected: false,
        status: "未启用",
      },
      {
        id: "failure-distiller",
        label: "failure-distiller",
        kind: "skill",
        required: false,
        selected: false,
        status: "未启用",
      },
      {
        id: "memory-curator",
        label: "memory-curator",
        kind: "skill",
        required: false,
        selected: true,
        status: "已启用",
      },
    ]);
  });

  test("parses a selected id set back into component state", () => {
    const state = parseOptionalSelection(
      new Set([SUPERPOWERS_PLUGIN_SPEC, "ai-sensei", "memory-curator"]),
      new Set(["memory-curator"]),
    );
    expect(state).toEqual({
      superpowers: true,
      agents: new Set(["ai-sensei"]),
      skills: new Set(["memory-curator"]),
    });
  });

  test("disambiguates an id that collides with a skill name", () => {
    const state = parseOptionalSelection(new Set(["memory-curator"]), new Set(["memory-curator"]));
    expect(state).toEqual({ superpowers: false, agents: new Set(), skills: new Set(["memory-curator"]) });
  });

  test("reads target config and skills markers", async () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-optional-"));
    try {
      const openCodeDir = join(root, "opencode");
      mkdirSync(join(openCodeDir, "skills", "memory-curator"), { recursive: true });
      writeFileSync(join(openCodeDir, "skills", "memory-curator", SKILL_MANAGED_MARKER), SKILL_MANAGED_CONTENT, "utf8");
      writeFileSync(
        join(openCodeDir, "opencode.jsonc"),
        [
          "// Generated by ai-share. Do not edit directly; change config/*.yaml instead.",
          JSON.stringify(
            {
              plugin: [SUPERPOWERS_PLUGIN_SPEC],
              agent: { "ai-sensei": { description: "d", mode: "subagent", prompt: "p" } },
            },
            null,
            2,
          ),
          "",
        ].join("\n"),
      );
      const paths = buildGeneratorPaths(root, { HOME: join(root, "home"), OPENCODE_CONFIG_DIR: openCodeDir });
      const state = await readTargetOptionalState(paths, {
        agentIds: ["fallback-agent"],
        skillNames: ["fallback-skill"],
      });
      expect(state).toEqual({
        superpowers: true,
        agents: new Set(["ai-sensei"]),
        skills: new Set(["memory-curator"]),
      });
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("enables all agents and skills by default when target config is missing", async () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-optional-missing-"));
    try {
      const openCodeDir = join(root, "opencode");
      const paths = buildGeneratorPaths(root, { HOME: join(root, "home"), OPENCODE_CONFIG_DIR: openCodeDir });
      const state = await readTargetOptionalState(paths, {
        agentIds: ["ai-sensei", "ai-share-commit-operator"],
        skillNames: ["memory-curator", "failure-distiller"],
      });
      expect(state).toEqual({
        superpowers: false,
        agents: new Set(["ai-sensei", "ai-share-commit-operator"]),
        skills: new Set(["memory-curator", "failure-distiller"]),
      });
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("throws a descriptive error when the target config is corrupt", () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-optional-corrupt-"));
    try {
      const openCodeDir = join(root, "opencode");
      mkdirSync(openCodeDir, { recursive: true });
      writeFileSync(join(openCodeDir, "opencode.jsonc"), "{ not valid jsonc", "utf8");
      const paths = buildGeneratorPaths(root, { HOME: join(root, "home"), OPENCODE_CONFIG_DIR: openCodeDir });
      const statePromise = readTargetOptionalState(paths, { agentIds: [], skillNames: [] });
      expect(statePromise).rejects.toThrow(/目标 OpenCode 配置解析失败/);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
