import type { TriRoleProfile } from "../tri-role.ts";

// GitHub Copilot reads .github/copilot-instructions.md for repository-level AI instructions
export function generateCopilotInstructions(profile: TriRoleProfile): string {
  const lines: string[] = [
    `# GitHub Copilot Instructions`,
    ``,
    `<!-- Generated by ai-share tri-role protocol adapter -->`,
    `<!-- Profile: ${profile.profile_id}${profile.name ? ` (${profile.name})` : ""} -->`,
    ``,
    `## Model Preferences`,
  ];

  lines.push(`- Primary coding tasks should use reasoning capabilities similar to ${profile.roles.primary.model}`);
  lines.push(
    `- Complex analysis and architecture decisions benefit from deeper reasoning like ${profile.roles.reasoning.model}`,
  );
  lines.push(`- Quick searches and refactoring can use lightweight models like ${profile.roles.fast.model}`);

  if (profile.compaction?.max_input_tokens) {
    lines.push(``);
    lines.push(`## Context Management`);
    lines.push(`- Keep context under ${profile.compaction.max_input_tokens} tokens`);
    if (profile.compaction.threshold) {
      lines.push(`- Summarize when context exceeds ${profile.compaction.threshold} tokens`);
    }
  }

  if (profile.strategies) {
    lines.push(``);
    lines.push(`## Project Strategies`);
    lines.push("```json");
    lines.push(JSON.stringify(profile.strategies, null, 2));
    lines.push("```");
  }

  lines.push(``);
  return lines.join("\n") + "\n";
}
