import type { TriRoleProfile } from "../tri-role.ts";

// .cursorrules is JSONC (JSON with comments) containing Cursor AI configuration
export function generateCursorRules(profile: TriRoleProfile): string {
  const comments = [
    `// Generated by ai-share tri-role protocol adapter`,
    `// Profile: ${profile.profile_id}${profile.name ? ` (${profile.name})` : ""}`,
    `// Date: ${new Date().toISOString().split("T")[0]}`,
    ``,
  ];

  const rules: Record<string, unknown> = {};

  // Model configuration
  rules.ai = {
    model: profile.roles.primary.model,
    fallbackModels: [profile.roles.reasoning.model, profile.roles.fast.model],
  };

  // Context preferences
  if (profile.compaction) {
    rules.context = {
      maxTokens: profile.compaction.max_input_tokens,
      compactionThreshold: profile.compaction.threshold,
    };
  }

  // Strategy hints
  if (profile.strategies) {
    rules.strategies = profile.strategies;
  }

  const jsonContent = JSON.stringify(rules, null, 2);
  return comments.join("\n") + jsonContent + "\n";
}
