import { describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { NATIVE_SKILLS } from "./cli/native-skills.ts";

const projectRoot = resolve(import.meta.dir, "..");

describe("generator install contract", () => {
  test("generates owned Codex files idempotently without a runtime manifest", () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-gen-"));
    const home = join(root, "home");
    const codexHome = join(root, "codex-home");

    try {
      const first = runGenerator(home, codexHome);
      expect(first.status).toBe(0);
      expect(first.stdout).toContain("actions=");

      const config = readFileSync(join(codexHome, "config.toml"), "utf8");
      expect(config).toStartWith("# Generated by ai-share.");
      expect(config).toContain('model_provider = "codexapis"');
      expect(config).toContain("[model_providers.codexapis]");
      expect(config).not.toContain("[model_providers.packyapi]");
      expect(readFileSync(join(codexHome, "AGENTS.md"), "utf8")).toContain("This file is generated by ai-share.");
      expect(readFileSync(join(codexHome, ".env"), "utf8")).toContain("# BEGIN ai-share managed env");
      const commitAgent = readFileSync(join(codexHome, "agents", "ai-share-commit-operator.toml"), "utf8");
      expect(commitAgent).toStartWith("# Generated by ai-share.");
      expect(commitAgent).toContain('name = "ai-share-commit-operator"');
      expect(commitAgent).toContain('description = "ai-share 的提交执行官"');
      expect(commitAgent).toContain('model = "gpt-5.5"');
      expect(commitAgent).toContain('model_reasoning_effort = "low"');
      expect(() => Bun.TOML.parse(commitAgent)).not.toThrow();
      for (const skill of NATIVE_SKILLS) {
        expect(readFileSync(join(codexHome, "skills", skill.name, "SKILL.md"), "utf8")).toBe(skill.content);
        expect(readFileSync(join(codexHome, "skills", skill.name, ".ai-share-managed"), "utf8")).toBe("ai-share\n");
      }
      expect(existsSync(join(codexHome, "ai-share.runtime.json"))).toBe(false);
      expect(existsSync(join(home, "ai-workspace"))).toBe(false);

      const before = snapshotGeneratedFiles(codexHome);
      const second = runGenerator(home, codexHome);
      expect(second.status).toBe(0);
      expect(second.stdout).toContain("actions=0");
      expect(snapshotGeneratedFiles(codexHome)).toEqual(before);

      const switched = runGenerator(home, codexHome, ["--provider", "packyapi"]);
      expect(switched.status).toBe(0);
      const switchedConfig = readFileSync(join(codexHome, "config.toml"), "utf8");
      expect(switchedConfig).toContain('model_provider = "packyapi"');
      expect(switchedConfig).toContain("[model_providers.packyapi]");
      expect(switchedConfig).not.toContain("[model_providers.codexapis]");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("fails atomically on an unowned collision and allows explicit adoption", () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-gen-collision-"));
    const home = join(root, "home");
    const codexHome = join(root, "codex-home");
    const configPath = join(codexHome, "config.toml");

    try {
      mkdirSync(codexHome, { recursive: true });
      writeFileSync(configPath, "# user config\n", { encoding: "utf8", flag: "wx" });
      const rejected = runGenerator(home, codexHome);
      expect(rejected.status).not.toBe(0);
      expect(rejected.stderr).toContain("未受管目标");
      expect(readFileSync(configPath, "utf8")).toBe("# user config\n");
      expect(existsSync(join(codexHome, "AGENTS.md"))).toBe(false);
      expect(existsSync(join(codexHome, "skills"))).toBe(false);

      const adopted = runGenerator(home, codexHome, ["--force"]);
      expect(adopted.status).toBe(0);
      expect(readFileSync(configPath, "utf8")).toStartWith("# Generated by ai-share.");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("dry-run performs no writes", () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-gen-dry-"));
    const home = join(root, "home");
    const codexHome = join(root, "codex-home");
    try {
      const result = runGenerator(home, codexHome, ["--dry-run"]);
      expect(result.status).toBe(0);
      expect(result.stdout).toContain("PLAN CREATE");
      expect(existsSync(codexHome)).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

function runGenerator(home: string, codexHome: string, args: readonly string[] = []) {
  return spawnSync(process.execPath, [resolve(projectRoot, "src", "generate-user-config.ts"), ...args], {
    cwd: projectRoot,
    encoding: "utf8",
    env: generatorEnv(home, codexHome),
  });
}

function generatorEnv(home: string, codexHome: string): NodeJS.ProcessEnv {
  const env: Record<string, string | undefined> = {
    ...process.env,
    HOME: home,
    USERPROFILE: home,
    CODEX_HOME: codexHome,
  };
  delete env.AI_SHARE_PROVIDER;
  delete env.AI_SHARE_TASK;
  return env;
}

function snapshotGeneratedFiles(codexHome: string): Record<string, string> {
  const snapshot: Record<string, string> = {
    "config.toml": readFileSync(join(codexHome, "config.toml"), "utf8"),
    ".env": readFileSync(join(codexHome, ".env"), "utf8"),
    "AGENTS.md": readFileSync(join(codexHome, "AGENTS.md"), "utf8"),
    "agents/ai-share-commit-operator.toml": readFileSync(
      join(codexHome, "agents", "ai-share-commit-operator.toml"),
      "utf8",
    ),
  };
  for (const skill of NATIVE_SKILLS) {
    snapshot[`skills/${skill.name}/SKILL.md`] = readFileSync(join(codexHome, "skills", skill.name, "SKILL.md"), "utf8");
    snapshot[`skills/${skill.name}/.ai-share-managed`] = readFileSync(
      join(codexHome, "skills", skill.name, ".ai-share-managed"),
      "utf8",
    );
  }
  return snapshot;
}
