import { describe, expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { NATIVE_SKILLS } from "./cli/native-skills.ts";
import type { OpenCodeConfig } from "./types.ts";

const projectRoot = resolve(import.meta.dir, "..");

describe("generator install contract", () => {
  test("generates owned OpenCode files idempotently and switches the selected provider", () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-gen-"));
    const home = join(root, "home");
    const openCodeDir = join(root, "opencode-home");

    try {
      const first = runGenerator(home, openCodeDir);
      expect(first.status).toBe(0);
      expect(first.stdout).toContain("actions=");

      const configPath = join(openCodeDir, "opencode.jsonc");
      const output = readFileSync(configPath, "utf8");
      expect(output).toStartWith("// Generated by ai-share.");
      const config = JSON.parse(output.slice(output.indexOf("{"))) as unknown as OpenCodeConfig;
      expect(config.model).toBe("codexapis/gpt-5.6-sol");
      expect(config.enabled_providers).toEqual(["codexapis"]);
      expect(Object.keys(config.provider)).toEqual(["codexapis"]);
      expect(config.agent["ai-share-commit-operator"]?.mode).toBe("subagent");
      expect(config.agent["ai-share-commit-operator"]?.model).toBe("codexapis/gpt-5.5");
      expect(readFileSync(join(openCodeDir, ".env"), "utf8")).toContain("# BEGIN ai-share managed env");
      expect(readFileSync(join(home, ".local", "bin", "aioc.ts"), "utf8")).toContain(
        "Generated by ai-share OpenCode launcher.",
      );
      expect(readFileSync(join(home, ".local", "bin", "aioc.cmd"), "utf8")).toContain("aioc.ts");
      for (const skill of NATIVE_SKILLS) {
        expect(readFileSync(join(openCodeDir, "skills", skill.name, "SKILL.md"), "utf8")).toBe(skill.content);
        expect(readFileSync(join(openCodeDir, "skills", skill.name, ".ai-share-managed"), "utf8")).toBe("ai-share\n");
      }

      const before = snapshotGeneratedFiles(openCodeDir);
      const second = runGenerator(home, openCodeDir);
      expect(second.status).toBe(0);
      expect(second.stdout).toContain("actions=0");
      expect(snapshotGeneratedFiles(openCodeDir)).toEqual(before);

      const switched = runGenerator(home, openCodeDir, ["--provider", "packyapi"]);
      expect(switched.status).toBe(0);
      const switchedOutput = readFileSync(configPath, "utf8");
      const switchedConfig = JSON.parse(switchedOutput.slice(switchedOutput.indexOf("{"))) as {
        model: string;
        provider: Record<string, unknown>;
      };
      expect(switchedConfig.model).toBe("packyapi/gpt-5.6-sol");
      expect(Object.keys(switchedConfig.provider)).toEqual(["packyapi"]);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("fails atomically on an unowned config collision and allows explicit adoption", () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-gen-collision-"));
    const home = join(root, "home");
    const openCodeDir = join(root, "opencode-home");
    const configPath = join(openCodeDir, "opencode.jsonc");

    try {
      mkdirSync(openCodeDir, { recursive: true });
      writeFileSync(configPath, '{ "$schema": "https://opencode.ai/config.json" }\n', "utf8");
      const rejected = runGenerator(home, openCodeDir);
      expect(rejected.status).not.toBe(0);
      expect(rejected.stderr).toContain("未受管目标");
      expect(readFileSync(configPath, "utf8")).toStartWith("{");
      expect(existsSync(join(openCodeDir, "skills"))).toBe(false);

      const adopted = runGenerator(home, openCodeDir, ["--force"]);
      expect(adopted.status).toBe(0);
      expect(readFileSync(configPath, "utf8")).toStartWith("// Generated by ai-share.");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("dry-run performs no writes", () => {
    const root = mkdtempSync(join(tmpdir(), "ai-share-gen-dry-"));
    const home = join(root, "home");
    const openCodeDir = join(root, "opencode-home");
    try {
      const result = runGenerator(home, openCodeDir, ["--dry-run"]);
      expect(result.status).toBe(0);
      expect(result.stdout).toContain("PLAN CREATE");
      expect(existsSync(openCodeDir)).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

function runGenerator(home: string, openCodeDir: string, args: readonly string[] = []) {
  return spawnSync(process.execPath, [resolve(projectRoot, "src", "generate-user-config.ts"), ...args], {
    cwd: projectRoot,
    encoding: "utf8",
    env: generatorEnv(home, openCodeDir),
  });
}

function generatorEnv(home: string, openCodeDir: string): NodeJS.ProcessEnv {
  const env: Record<string, string | undefined> = {
    ...process.env,
    HOME: home,
    USERPROFILE: home,
    OPENCODE_CONFIG_DIR: openCodeDir,
  };
  delete env.AI_SHARE_PROVIDER;
  delete env.AI_SHARE_TASK;
  return env;
}

function snapshotGeneratedFiles(openCodeDir: string): Record<string, string> {
  const snapshot: Record<string, string> = {
    "opencode.jsonc": readFileSync(join(openCodeDir, "opencode.jsonc"), "utf8"),
    ".env": readFileSync(join(openCodeDir, ".env"), "utf8"),
  };
  for (const skill of NATIVE_SKILLS) {
    snapshot[`skills/${skill.name}/SKILL.md`] = readFileSync(
      join(openCodeDir, "skills", skill.name, "SKILL.md"),
      "utf8",
    );
    snapshot[`skills/${skill.name}/.ai-share-managed`] = readFileSync(
      join(openCodeDir, "skills", skill.name, ".ai-share-managed"),
      "utf8",
    );
  }
  return snapshot;
}
